src/cli/main.cpp, src/package_manager/impl/package_manager.cpp
ll-cli 无法连接到仓库场景query提示信息不准
Log:
=> fix: ll-cli 无法连接到仓库场景query提示信息不准

src/module/util/xdg.cpp
parse semicolon when app run.
Log:
=> fix: parse semicolon

debian/changelog
=> chore: bump version to 1.3.3.23-1

LICENSE, README.md, README.zh_CN.md
Log:
Change-Id: Iebb6a11025a7ab5c49b2324e3976d1c19aba6b1d
=> feat: add license

debian/changelog, src/builder/builder/depend_fetcher.cpp, src/builder/builder/linglong_builder.cpp, src/cli/main.cpp, src/module/dbus_ipc/org.deepin.linglong.PackageManager.xml, src/module/repo/ostree_repo.cpp, src/module/util/http/httpclient.cpp, src/module/util/http/httpclient.h, src/package_manager/impl/package_manager.cpp, src/package_manager/impl/package_manager.h, src/package_manager/impl/package_manager_p.h, test/module/util/httpclient_test.cpp
=> chore: bump version to 1.3.4-1

src/cli/main.cpp, src/module/repo/ostree_repohelper.h, src/module/util/log/log_handler_p.h, src/package_manager/impl/package_manager.cpp, src/package_manager/impl/package_manager_flatpak_impl.h, src/package_manager/impl/package_manager_p.h
=> feat: modify repo增加nodbus方式

debian/changelog, src/module/runtime/app.cpp
use the exec parameter in the desktop file instead of the last value
Log:
=> fix: failed to run org.deepin.manual

src/builder/resource/builder.yaml
use the correct remote repository
Log: update remote repository
=> chore: update remote repository

src/module/runtime/app.cpp
mount ${HOME}/.local/share/icons into container
Log: none
=> fix: shortcuts created by some apps have no icons

src/builder/builder/builder_config.cpp, src/builder/builder/depend_fetcher.cpp, src/builder/builder/linglong_builder.cpp, src/module/repo/ostree_repo.cpp, src/module/repo/ostree_repo.h, src/module/util/file.h
support multiple repositories;
fix the parameter of exec parsing failed;
fix some data files of application could not be found.
=> support multiple repositories and fix some bugs

src/builder/builder/builder.h, src/builder/builder/linglong_builder.cpp, src/builder/builder/linglong_builder.h, src/builder/main.cpp, src/module/util/runner.h
track the latest submisson and update it in linglong.yaml
Log:
=> feat: track the latest submission

src/module/repo/ostree_repo.cpp, src/module/util/version/semver.h, src/package_manager/CMakeLists.txt, src/package_manager/impl/package_manager.cpp
1. optimize the prompt of builder
2. ll-cli update the appliction to  the wrong version
=> bugfix-20230213

src/builder/builder/builder_config.cpp, src/builder/resource.qrc
- feat: ll-builder support project-wide config
- refactor: BuilderConfig::instance
=> fix builder config

src/module/runtime/app.cpp
=> doc: add a comment

src/module/runtime/app.cpp, src/package_manager/impl/package_manager.cpp
get the latest base of runtime.
Log:
=> fix: download base failed

misc/linglong/builder/templates/autotools.yaml, misc/linglong/builder/templates/cmake.yaml, misc/linglong/builder/templates/default.yaml, misc/linglong/builder/templates/qmake.yaml, src/builder/builder/builder.cpp, src/builder/builder/project.cpp, src/builder/builder/project.h
We should export some build flags before the build begins.
Log:
=> feat(builder): support some build flags

src/builder/builder/linglong_builder.cpp
This reverts commit eef1fa9544c7da932ddef9fe72c47538462575ca.
=> Revert "fix: some parameter of exec parsing failed"

src/module/repo/ostree_repo.cpp
For details, check comments in the code.
=> fix: workround for downloading the huge base

src/package_manager/impl/package_manager.cpp
=> fix: ensure repo defore modify repo

src/builder/builder/builder_config.cpp, src/builder/builder/builder_config.h, src/builder/builder/depend_fetcher.cpp, src/builder/main.cpp, src/module/repo/ostree_repo.cpp
Backport some builder feature back to 1.3.x for OBS build
=> Support offline params

.gitignore, INSTALL.md, README.md, README.zh_CN.md, debian/control
- update .gitignore for IDE.
- update README and INSTALL, fix markdownlint issue and spell mistake.
- remove libgdk-pixbuf2.0-dev.
Change-Id: I61e6586e6e91ccf7494f161f90ceb1a3ac3368a4
=> chore: fix some tiny issue for docs and depends

src/builder/main.cpp
=> chore: fix typos in main.cpp

src/package_manager/impl/package_manager.cpp
If the app is already installed, we should compare the local version with the remote version. And the remote version of app should not be installed if the local version is bigger than the remote version.
Log:
=> fix: install app with default verison is wrong

debian/changelog, src/package_manager/impl/package_manager.cpp
backport:
* fix: install app with default verison is wrong
=> Bump version to 1.3.8

src/cli/main.cpp, src/module/dbus_ipc/org.deepin.linglong.PackageManager.xml, src/package_manager/impl/package_manager.cpp, src/package_manager/impl/package_manager.h
=> feat: support display the current info of repo

src/package_manager/impl/package_manager.cpp
=> fix: incorrect prompt when installing non-app types

misc/linglong/builder/templates/strip.sh
=> fix: some file which is not ELF is also not stripped

debian/changelog, debian/control
=> chore: bump version to 1.4.0 UNRELEASED

.obs/workflows.yml, .reuse/dep5
for obs build(deepin_develop,debian,archlinux)
log:
=> chore(CI): Add obs workflow files

apps/ll-cli/src/main.cpp
This is a simple test by lxy.
- Edit an if clause.
- Unify all `addOptions()` and `addOptions()` into `addOptions()` in `apps/ll-cli/src/main.cpp`.
=> refactor: refactor test 

src/linglong/builder/builder_config.cpp, src/linglong/builder/builder_config.h, src/linglong/builder/source_fetcher.cpp, src/linglong/builder/source_fetcher.h, src/linglong/builder/source_fetcher_p.h
fix linuxdeepin/developer-center#5492
=> feat: archive fetcher support URL redirect

misc/scripts/upgrade-all.in
Related: linuxdeepin/developer-center#5561
=> fix(scripts): ignore error in xargs

debian/changelog, debian/linglong-bin.postinst, debian/linglong-bin.postrm, misc/scripts/upgrade-all.in
- fix: include debhelper in linglong-bin triggers
- chore: bump verison to 1.3.12
=> fix: update trigger

misc/scripts/upgrade-all.in
=> fix(scripts): correct command

src/linglong/repo/ostree_repohelper.cpp
=> fix(repo): set http2=false

debian/changelog, misc/scripts/upgrade-all.in
- fix(scripts): correct command
- chore: bump version to 1.3.13
=> backport #101

INSTALL.md
=> docs: update INSTALL.md

CMakeLists.txt
=> build: update version to 1.4.0

debian/changelog, src/builder/builder/linglong_builder.cpp, src/module/repo/ostree_repo.cpp, src/module/repo/ostree_repo.h, src/module/repo/ostree_repohelper.cpp
backport fix(repo): set http2=false
068e81cda7440c9aa6f9cc9023ef4fde586e0f55
=> Backport 20230919

CMakeLists.txt, apps/ll-builder/src/main.cpp, apps/ll-cli/src/main.cpp, apps/ll-package-manager/src/main.cpp, apps/ll-service/src/main.cpp, apps/ll-system-helper/src/main.cpp, debian/control, misc/scripts/create-linglong-dirs.in, src/linglong/repo/ostree_repohelper.cpp, src/linglong/repo/repo_client.cpp, src/linglong/util/configure.h.in, src/linglong/utils/global/CMakeLists.txt, src/linglong/utils/global/initialize.cpp, src/linglong/utils/global/initialize.h
- build: remove unused CMAKE option
- feat: use journald to logging
- fix: check network reply
- refact: use nullptr
=> some little fixes

README.zh_CN.md
=> doc: Update README.zh_CN.md

.reuse/dep5, CMakeLists.txt, OWNERS, apps/llpkg/CMakeLists.txt, cmake/PFL.cmake, debian/rules, tools/upgrade-cpm.sh, tools/upgrade-pfl.sh
- chore: update debian/rules
- chore: add tools
- chore: update PFL.cmake
- build: manually add alias for yaml-cpp
=> some little refact

misc/linglong/builder/templates/example.yaml, src/linglong/builder/source_fetcher.cpp
support git pull submodule.
update example.yaml.
=> support git to pull submodules & update example.yaml 

debian/changelog, src/builder/builder/source_fetcher.cpp, src/builder/builder/source_fetcher.h, src/builder/builder/source_fetcher_p.h, src/builder/resource/example.yaml
- support git pull submodule.
- update example.yaml.
-  support URL redirect and more suffixs.
=> Fix 20231013

CMakeLists.txt, src/linglong/package_manager/package_manager.cpp
- fix: correct constants in configure.h.in
- fix: get right base to install
=> fix base download

src/linglong/runtime/app.cpp
Unchecked access to optional value.
=> fix: crash

src/package_manager/impl/package_manager.cpp
we should sort the runtime info by version again.
Log:
=> fix: failed to get the base environment

misc/linglong/builder/templates/autotools.yaml, misc/linglong/builder/templates/cmake.yaml, misc/linglong/builder/templates/default.yaml, misc/linglong/builder/templates/qmake.yaml, src/linglong/builder/project.cpp, src/linglong/builder/project.h
=> chore: correct typos for "environment"

apps/ll-cli/src/main.cpp, apps/ll-package-manager/src/main.cpp, apps/ll-system-helper/src/main.cpp, src/linglong/cli/printer.cpp, src/linglong/job_manager/job_manager.cpp, src/linglong/job_manager/job_manager.h, src/linglong/repo/ostree_repo.cpp, src/linglong/repo/ostree_repo.h, src/linglong/repo/repo.h
- fix: register job manager
- refact: remove JobManagerPrivate
- fix: correct console printer
- fix: use Qt::QueuedConnection
=> Fix some bugs

CMakeLists.txt, debian/control, src/linglong/package/architecture.cpp, src/linglong/package/architecture.h, src/linglong/package/fuzz_reference.cpp, src/linglong/package/fuzz_reference.h, src/linglong/package/module.cpp, src/linglong/package/module.h, src/linglong/package/reference.cpp, src/linglong/package/reference.h, src/linglong/package/version.cpp, src/linglong/package/version.h, src/linglong/package/version_range.cpp, src/linglong/package/version_range.h, tests/CMakeLists.txt, tests/src/linglong/package/reference_test.cpp, tests/src/linglong/package/version_range_test.cpp, tests/src/linglong/package/version_test.cpp
introduce new Reference to replace old Ref.
=> refact: introduce new Reference

src/linglong/builder/linglong_builder.cpp, src/linglong/builder/project.cpp, src/linglong/builder/project.h
=> refact(builder): merge Project and ProjectPrivate

debian/changelog, debian/linglong-bin.postinst, debian/linglong-bin.preinst
remove linglong.sh and 21linglong which in old package.
Log:
=> chore: remove old configs before install linglong

src/linglong/cli/cli.cpp, src/linglong/package/architecture.cpp, src/linglong/package/fuzz_reference.cpp, src/linglong/package/module.cpp, src/linglong/package/reference.cpp, src/linglong/package/version.cpp, src/linglong/package/version_range.cpp, src/linglong/service/app_manager.h, src/linglong/utils/dbus/register.h, src/linglong/utils/error/error.h, src/linglong/utils/xdg/desktop_entry.h, tests/src/linglong/utils/error/result_test.cpp
=> refact(utils): update error handling macros

src/linglong/builder/project.cpp
=> chore: correct a typo in project.cpp

src/linglong/runtime/app.cpp
Temporarily mount the host /tmp into the container.
Log:
=> fix: some app failed to share data by /tmp

apps/ll-package-manager/src/main.cpp, apps/ll-service/src/main.cpp, src/linglong/repo/repo_client.cpp
=> fix some crash issues

apps/ll-builder/src/main.cpp, src/linglong/builder/builder.h, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h, src/linglong/builder/project.cpp
support operation of export layer
=> feat: support operation of export layer

apps/ll-builder/src/main.cpp, src/linglong/builder/builder.h, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
Import layer with ll-builder import <layer path>.
Log:
=> feat: support the operation of import layer

apps/ll-cli/src/main.cpp, src/linglong/cli/cli.cpp, src/linglong/cli/cli.h, src/linglong/cli/json_printer.cpp, src/linglong/cli/json_printer.h, src/linglong/cli/printer.cpp, src/linglong/cli/printer.h
Print info from layer with ll-cli info <layer path>.
Log:
=> feat: support the operation of print info from layer

api/dbus/org.deepin.linglong.PackageManager1.xml, src/linglong/cli/cli.cpp, src/linglong/dbus_ipc/param_option.h, src/linglong/package/layer_packager.cpp, src/linglong/package_manager/package_manager.cpp, src/linglong/package_manager/package_manager.h
Install layer with ll-cli install <layer path>.
=> feat: support the operation of install layer

src/linglong/package/fuzz_reference.cpp, src/linglong/package/fuzz_reference.h, src/linglong/package/reference.cpp, src/linglong/package/reference.h, src/linglong/utils/error/error.h, tests/src/linglong/package/reference_test.cpp
- feat: and new error wrap macros
- refact: remove module from reference
=> remove module from reference

src/linglong/repo/ostree_repo.cpp
=> fix: ensure layer dir before checkout

src/linglong/repo/ostree_repo.cpp, src/linglong/util/app_status.cpp
=> fix: do not pass version="latest" when start app

src/linglong/repo/ostree_repo.cpp
do not need to retry when pull data from remote repo
=> fix: remove 30 times retry for pull

src/linglong/builder/linglong_builder.cpp
uidMappings and gidMappings not init by std::optional
=> fix: uidMappings and gidMappings not init

src/linglong/repo/ostree_repo.cpp
appid  is filled with reference
=> fix: appid is filled with reference

src/linglong/repo/ostree_repo.cpp
set gpg-verify is false for ostree_repo_remote_change
=> fix: set gpg-verify to false not work

src/linglong/repo/ostree_repo.cpp
=> fix: add missing semicolon

src/linglong/cli/cli.cpp
=> refact(cli): disable enter

src/linglong/runtime/app.cpp
- fix: appId -> appID
- fix: always create empty json array in dbus proxy config
=> fix some json key issue in dbus proxy config

src/linglong/builder/linglong_builder.cpp
can not commit directory to repo when the reference lost the channel field
=> fix: ref without channel

api/dbus/org.deepin.linglong.PackageManager1.xml, src/linglong/cli/cli.cpp, src/linglong/package_manager/package_manager.cpp, src/linglong/package_manager/package_manager.h
=> fix: The issues of PM lacking permission to read layer file

misc/scripts/upgrade-all.in, src/linglong/cli/cli.cpp
- fix: update upgrade-all script
- fix: not pass version as "latest" when upgrade
=> fix: upgrade

apps/ll-builder/src/main.cpp, src/linglong/builder/linglong_builder.cpp
使用 fromYAML 读取 linglong 文件
之前的方法有解析失败的情况
Log:
=> feat: Use util::fromYAML in builder

src/linglong/builder/linglong_builder.cpp
=> fix: devel ref branch name error

src/linglong/service/app_manager.cpp
=> feat: support start application from the new default channel

apps/ll-builder/src/main.cpp, misc/CMakeLists.txt, misc/linglong/builder/templates/appimage.yaml, misc/linglong/builder/templates/makeimage.yaml, src/linglong/builder/builder.h, src/linglong/builder/builder_templates.qrc, src/linglong/builder/depend_fetcher.cpp, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h, src/linglong/builder/project.cpp, src/linglong/builder/source_fetcher.cpp, src/linglong/repo/ostree_repo.cpp
help ll-builder to build linglong package with appimage file
=> feat: add transfer appimage to linglong

src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
在commit时,判断的ret是否有值,但返回的却是err这个变量
Log:
=> fix: Commit failure incorrectly indicates build success

misc/CMakeLists.txt, misc/linglong/builder/templates/appimage.yaml, src/linglong/builder/project.cpp
display build details in linglong.yaml for developer
Log:
=> chore: display build details in linglong.yaml

src/linglong/builder/depend_fetcher.cpp, src/linglong/builder/depend_fetcher.h, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/source_fetcher.cpp, src/linglong/repo/ostree_repo.cpp, src/linglong/repo/ostree_repo.h
1 support print progress while pulling dependency
2 format print information
=> support print progress while pulling dependency

src/linglong/repo/ostree_repo.cpp
=> fix: avoid Dangling pointer

debian/control
We need use erofsfuse to handle the layer file.
Log:
=> chore: add erofsfuse to depends

debian/control
=> chore: replace linglong-dbus-proxy

debian/linglong-bin.postinst
Related: linuxdeepin/developer-center#7033
=> chore: remove old xsession script

debian/changelog
=> chore: bump version to 1.4.3-1

apps/ll-builder/src/main.cpp, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h, src/linglong/repo/ostree_repo.cpp, src/linglong/repo/ostree_repo.h, src/linglong/repo/repo.h, src/linglong/service/app_manager.cpp, src/linglong/service/app_manager.h
ll-builder使用AppManager运行应用, 避免开发测试和实际运行不一致
Log:
=> feat: ll-builder uses AppManager to run applications

debian/linglong-builder.install, misc/CMakeLists.txt, misc/bash_completion/ll-builder
=> feat: add bash completion for ll-builder

src/linglong/package/layer_packager.cpp
=> fix: typo in layer_packager.cpp

misc/bash_completion/ll-cli
=> fix: update bash completion for ll-cli

misc/linglong/builder/templates/strip.sh
=> feat: clean up temporary file generated by build

misc/scripts/upgrade-all.in
自动更新脚本添加休眠时间,避免因并发问题影响用户cli操作
Log:
=> feat: add sleep to upgrade-all to avoid impacting CLI operations

src/linglong/builder/linglong_builder.cpp
if the current enviroment include some variables about network proxy, we should also set them up in the build enviroment.
Log:
=> fix: set the env variable of network proxy in builder

misc/bash_completion/ll-cli, src/linglong/cli/cli.cpp
=> fix: add 'll-cli repo list' to usage and completion

apps/ll-builder/src/main.cpp, src/linglong/builder/builder_config.cpp, src/linglong/builder/builder_config.h, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/project.cpp, src/linglong/builder/project.h
=> feat(ll-builder): start support cross-compilation

src/linglong/builder/depend_fetcher.cpp
=> fix: use lambda in c++11 standard

tests/src/linglong/cli/cli_test.cpp
=> test: update cli test

CMakeLists.txt
=> fix: add missing find_package for spdlog

src/linglong/builder/linglong_builder.cpp
修复无runtime的应用不能使用builder run启动
Log:
=> fix: App without runtime cannot use builder run

apps/ll-builder/src/main.cpp, apps/ll-cli/src/main.cpp, apps/ll-service/src/main.cpp
=> feat: Check if crun exists

src/linglong/runtime/app.cpp
在命令行参数指定exec后, 无需再查找desktop文件
避免无法启动无desktop文件的应用
Log:
=> fix: App cannot run without desktop file

misc/scripts/fetch-git-repo, src/linglong/repo/ostree_repo.cpp
=> feat: remoteLatestRef should return error when app cannot be found

src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h, src/linglong/runtime/app.cpp, src/linglong/runtime/app.h
使用overlayfs挂载rootfs，避免创建的挂载点污染base文件
=> feat: mount container rootfs using overlayfs

apps/ll-builder/src/main.cpp, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
support appimage url and hash to convert to linglong .layer(.uab)
Log:
=> feat: appimage support url convert

docs/pages/en/guide/ll-builder/convert.md, docs/pages/en/guide/ll-builder/introduction.md, docs/pages/guide/ll-builder/convert.md, docs/pages/guide/ll-builder/introduction.md
added usage documentation of appimage convert
Log:
=> chore: add appimage convert docs

apps/ll-builder/src/main.cpp, src/linglong/builder/builder_config.cpp, src/linglong/builder/builder_config.h, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
=> feat: builder support set environment variables using command args

apps/ll-builder/src/main.cpp, src/linglong/builder/builder.h, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
=> feat: split the build function

.gitmodules
=> fix: correct gitsubmodule

CMakeLists.txt, src/linglong/builder/linglong_builder.cpp, src/linglong/runtime/app.cpp, src/linglong/utils/command/ocppi-helper.cpp, src/linglong/utils/command/ocppi-helper.h
添加overlayfs挂载参数到容器的配置文件里
便于调试重现
Log:
=> feat: add overlayfs mount paramenters to annotations

CMakeLists.txt, api/dbus/org.deepin.linglong.PackageManager1.xml, apps/ll-cli/src/main.cpp, src/linglong/cli/cli.cpp, src/linglong/cli/cli.h, src/linglong/cli/json_printer.cpp, src/linglong/cli/json_printer.h, src/linglong/cli/printer.cpp, src/linglong/cli/printer.h, src/linglong/dbus_ipc/reply.h, src/linglong/package_manager/package_manager.cpp, src/linglong/package_manager/package_manager.h, src/linglong/package_manager/task.cpp, src/linglong/package_manager/task.h, src/linglong/repo/ostree_repo.cpp, src/linglong/repo/ostree_repo.h, src/linglong/repo/repo.h, tests/src/linglong/api/dbus/v1/mock_package_manager.h, tests/src/linglong/cli/cli_test.cpp
* use dbus signal to notify cli download progress
* support cancel downloading manually
* use eventloop instead of threadpool
=> refactor(package_manager): install and upgrade 

src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
=> feat: mount build helper

src/linglong/builder/builder_config.h
set offline default value to false
Log:
=> fix: offline status is error when fetch base

src/linglong/builder/linglong_builder.cpp, src/linglong/builder/project.cpp, src/linglong/builder/project.h, src/linglong/builder/source_fetcher.cpp
现在支持多个source, 但没有合理的将多个source映射到容器中
这个提交给source添加path字段,当指定path字段时,source会映射到容器的/sources/$path 未指定path时, 会使用source的哈希或生成uuid作为path使用
Log:
=> feat: source add path field

apps/ll-builder/src/main.cpp, src/linglong/builder/builder_config.h, src/linglong/builder/linglong_builder.cpp
构建支持跳过commit output, 跳过source fetch
便于快速调试
Log:
=> feat: support skip commit output

apps/ll-builder/src/main.cpp, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/project.h
export命令支持arch参数
build支持指定base架构
清理注释的代码
Log:
=> feat: export support arch parameter

misc/linglong/builder/config-check.sh, misc/linglong/builder/ldd-check.sh, misc/linglong/builder/main-check.sh
=> feat: add some check script for ll-builder

misc/scripts/fetch-dsc-repo, src/linglong/builder/builder_releases.qrc, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/source_fetcher.cpp, src/linglong/builder/source_fetcher.h, src/linglong/builder/source_fetcher_p.h
支持获取dsc格式的原料,便于从deb仓库构建应用
Log:
=> feat: support fetch dsc sources

debian/control
move some dependens to recomends
Log:
=> chore: adjust debian dependens

api/schema/v1.yaml, apps/ll-builder/src/main.cpp, src/linglong/api/types/v1/BuilderProject.hpp, src/linglong/api/types/v1/Generators.hpp
现在会固定将项目文件及映射到容器中, 不再需要写local
sources也就不再是必选项
Log:
=> feat: make the 'sources' field optional

src/linglong/package/fuzzy_reference.cpp
=> chore: add more error message

src/linglong/repo/ostree_repo.cpp
=> fix: correct url

src/linglong/repo/ostree_repo.cpp
=> fix: correct cdUp

src/linglong/builder/linglong_builder.cpp
=> fix: optional sources access

src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
=> feat: mount workdir to '/project' in the container

src/linglong/repo/ostree_repo.cpp
=> fix: correct creating parent directory of layerDir

misc/lib/linglong/container/config.d/10-basics.json
=> feat: use tmpfs mount /run directory

src/linglong/runtime/container.cpp
=> fix: run assert failed

api/schema/v1.yaml, src/linglong/api/types/v1/BuilderProject.hpp, src/linglong/api/types/v1/Generators.hpp, src/linglong/api/types/v1/PackageInfo.hpp, src/linglong/builder/linglong_builder.cpp, src/linglong/cli/cli.cpp
add command field to specify the running path for ll-cli or ll-build to start app
Log:
=> feat: add command field to specify the running path

apps/generators/90-legacy/src/main.cpp
com.360.browser-stable need apps-data/private/com.360.browser-stable dir to save authorization file
Log:
=> fix: com.360.browser-stable can not run normally

src/linglong/repo/ostree_repo.cpp
=> fix: error to assert dir

api/schema/v1.yaml, src/linglong/api/types/v1/BuilderProject.hpp, src/linglong/api/types/v1/Generators.hpp, src/linglong/api/types/v1/PackageInfo.hpp, src/linglong/builder/linglong_builder.cpp, src/linglong/cli/cli.cpp
command field not should require opt
Log:
=> fix: command field not should require opt

CMakeLists.txt, CMakePresets.json, apps/ll-builder/src/main.cpp, misc/CMakeLists.txt, misc/libexec/linglong/fetch-git-repo, misc/share/linglong/config.yaml, src/linglong/builder/builder_releases.qrc, src/linglong/builder/config.cpp, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h, src/linglong/builder/source_fetcher.cpp, src/linglong/repo/config.cpp, src/linglong/repo/ostree_repo.cpp, src/linglong/runtime/container.cpp, src/linglong/runtime/container_builder.cpp, src/linglong/utils/command/env.cpp
=> fix: ll-build build error

misc/share/linglong/config.yaml
=> fix: missing default config.yaml

api/schema/v1.yaml, src/linglong/api/types/v1/BuilderProject.hpp, src/linglong/api/types/v1/Generators.hpp, src/linglong/builder/linglong_builder.cpp, tools/codegen.sh
Generate custom mount points in info.json to mount what the user wants at runtime
=> feat: add new property `permissions`

api/schema/v1.yaml, apps/ll-builder/src/main.cpp, misc/libexec/linglong/fetch-dsc-repo, src/linglong/api/types/v1/BuilderProjectSource.hpp, src/linglong/api/types/v1/Generators.hpp, src/linglong/builder/linglong_builder.cpp, src/linglong/repo/ostree_repo.cpp
修复源码拉取错误
源码应该存放在linglong/sources的子目录
Log:
=> fix: source fetch error

src/linglong/builder/linglong_builder.cpp, src/linglong/package/architecture.cpp, src/linglong/package/architecture.h
=> feat: support build application on LoongArch64

src/linglong/builder/linglong_builder.cpp
=> fix(ll-builder): link shared files to entries failed

debian/linglong-bin.install, misc/CMakeLists.txt, misc/script/linglong.sh
XDG_DATA_DIRS environment variable maybe be unset by a program when login, so we must set it again
Log:
=> fix: XDG_DATA_DIRS env is unset

src/linglong/builder/linglong_builder.cpp, src/linglong/repo/ostree_repo.cpp
=> fix: link files failed in exportReference()

misc/libexec/linglong/fetch-dsc-repo, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/source_fetcher.cpp, src/linglong/builder/source_fetcher.h
修复'file'和'archive'类型的source下载
Log:
=> fix: source fetch failure when kind is 'file' or 'archive'

apps/ll-builder/src/main.cpp, src/linglong/builder/linglong_builder.cpp, src/linglong/builder/linglong_builder.h
=> feat: ll-builder adds system environment variables

src/linglong/builder/linglong_builder.cpp, src/linglong/repo/ostree_repo.cpp
=> fix: Wrong path to temporary repo

misc/libexec/linglong/app-conf-generator
=> fix: missing X-linglong after patch desktop

src/linglong/builder/linglong_builder.cpp, src/linglong/cli/cli.cpp, src/linglong/runtime/container.cpp
=> feat: ll-cli support setting enviroment variables from profile.d

src/linglong/builder/linglong_builder.cpp, src/linglong/package_manager/task.cpp, src/linglong/package_manager/task.h, src/linglong/repo/ostree_repo.cpp
=> fix: ll-builder progress display for pull dependency

misc/libexec/linglong/app-conf-generator, src/linglong/builder/linglong_builder.cpp
fix typo;
set TryExec to ll-cli;
set correct package size in info.json
=> fix: fix minor bugs

src/linglong/builder/linglong_builder.cpp, src/linglong/package_manager/task.cpp
builder应该查找develop包而不是runtime包
Log:
=> fix: builder should not found runtime package

.gitignore, src/linglong/package_manager/package_manager.cpp, src/linglong/repo/ostree_repo.cpp
1. ignore debian/tmp ;
2. failed remove shared files;
3. app will be removed after upgrade.
=> fix: ignore debian/tmp & failed remove shared files & upgrade failed

libs/linglong/src/linglong/package/layer_packager.cpp
umount error dir in LayerPackager destruct
Log:
=> fix: umount error dir in LayerPackager destruct

apps/ll-box/src/container/container.cpp
=> refact(ll-box): void unknow env

libs/linglong/src/linglong/runtime/container.cpp, libs/linglong/src/linglong/runtime/container_builder.cpp, libs/linglong/src/linglong/utils/global/initialize.cpp
=> chore: refine log level

apps/ll-box/README.md
=> docs(ll-box): move box readme here

apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/utils/global/initialize.cpp
- **chore: enable info logging and deprecate builder -v**
- **chore: move ll-builder user config location**
=> refine log

apps/ll-box/src/container/helper.cpp, apps/ll-box/src/container/helper.h, apps/ll-box/src/main.cpp
=> feat(ll-box): initial implementation of `list` and `kill`

misc/share/linglong/config.yaml
=> chore: modify repo to stable

.obs/workflows.yml
=> feat: CI/CD adding UOS 20 repository

apps/ll-box/src/container/container.cpp, apps/ll-box/src/util/platform.cpp, apps/ll-box/src/util/platform.h, libs/linglong/CMakeLists.txt
=> fix(ll-box): exit with -1 when init don't return 0

libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/json_printer.cpp, libs/linglong/src/linglong/cli/json_printer.h, libs/linglong/src/linglong/cli/printer.cpp, libs/linglong/src/linglong/cli/printer.h
ll-cli list support show tier of speciafy app
Log:
=> feat: ll-cli list support show tier of speciafy app

apps/ll-box/src/container/container.cpp, apps/ll-box/src/container/helper.cpp, apps/ll-box/src/main.cpp, debian/linglong-bin.install, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/runtime/container.cpp
=> fix: build failure on UOS 20

debian/control, misc/libexec/linglong/fetch-dsc-repo
linglong-builder add dependence
Log:
=> fix: linglong-builder dependence is missing

libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/printer.cpp
refactor ll-cli list --app to ll-cli info
Log:
=> refactor: refactor ll-cli list --app to ll-cli info

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/cli/json_printer.cpp, libs/linglong/src/linglong/cli/json_printer.h, libs/linglong/src/linglong/cli/printer.cpp, libs/linglong/src/linglong/cli/printer.h
New subcommand to display the exported files.
Log:
=> feat: support ll-cli content

.obs/workflows.yml, rpm/linglong.spec
=> feat: Building RPM packages with obs cicd

libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h
support ll-cli list(search) --type option
Log:
=> fix: ll-cli list(search) --type not valid

libs/linglong/src/linglong/builder/linglong_builder.cpp
=> feat: clean up unseless environment variables

api/schema/v1.yaml, apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/api/types/v1/BuilderConfig.hpp, libs/linglong/src/linglong/api/types/v1/Generators.hpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/package_manager/task.cpp, libs/linglong/src/linglong/package_manager/task.h, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/utils/error/error.h, tools/codegen.sh
builder支持跳过容器运行(构建), 用于只下载源码和依赖的时候使用
Log:
=> feat: support skip container run

debian/linglong-bin.postinst, debian/linglong-bin.preinst
=> chore: handle upgrade from old linglong

.reuse/dep5, api/schema/.gitignore, api/schema/v1.json, api/schema/v1.yaml, debian/linglong-bin.install, libs/linglong/src/linglong/cli/cli.cpp, misc/CMakeLists.txt
add description of api doc
Log:
=> docs: optimization api doc

rpm/linglong.spec
=> fix: fix rpm build

CMakeLists.txt
=> chore: use ll-box replace crun

libs/linglong/src/linglong/package_manager/package_manager.cpp
=> fix: ll-cli install foundation or runtime failed

apps/ll-box/src/container/container.cpp, apps/ll-box/src/container/mount/host_mount.cpp, apps/ll-box/src/container/mount/host_mount.h, libs/linglong/src/linglong/runtime/container.cpp
fix typo
Issue: https://github.com/linuxdeepin/linglong/issues/398
=> fix: add finalizeMounts to delay remount 

debian/linglong-bin.preinst
=> fix: correct mktemp in preinst

apps/ll-box/src/container/container.cpp, apps/ll-box/src/container/mount/host_mount.cpp, apps/ll-box/src/container/mount/host_mount.h, apps/ll-box/src/util/logger.h, libs/linglong/src/linglong/runtime/container.cpp
- **fix(box): correct spelling**
- **Revert "fix(box): move finalize mounts to beginning of pivot root"**
- **Revert "fix: add finalizeMounts to delay remount"**
=> Revert some buggy commits

CMakeLists.txt
This reverts commit ccf0c8a3e864e09d19b8084b77c4dcb0b872d41d.
=> Revert "chore: use ll-box replace crun"

debian/control
remove linglong-box depend
Log:
=> chore: remove linglong-box depend

debian/copyright
=> chore: update debian/copyright

docs/pages/en/guide/ll-builder/build.md, docs/pages/en/guide/ll-builder/create.md, docs/pages/en/guide/ll-builder/export.md, docs/pages/en/guide/ll-builder/manifests.md, docs/pages/en/guide/ll-cli/introduction.md, docs/pages/en/guide/ll-cli/query.md, docs/pages/en/guide/ll-cli/run.md, docs/pages/guide/ll-builder/build.md, docs/pages/guide/ll-builder/create.md, docs/pages/guide/ll-builder/export.md, docs/pages/guide/ll-builder/manifests.md, docs/pages/guide/ll-cli/introduction.md, docs/pages/guide/ll-cli/query.md, docs/pages/guide/ll-cli/run.md, misc/linglong/builder/templates/example.yaml
* 删除目前版本无法使用的玲珑构建文档
* 添加构建示例
Issue: https://github.com/linuxdeepin/developer-center/issues/8265
Log: update docs
=> chore: update docs

debian/changelog
release linglong 1.5.0
Lgo: update changelog
=> chore: release linglong 1.5.0

.reuse/dep5, debian/linglong-bin.install, debian/linglong-bin.postinst, debian/linglong-bin.preinst, misc/CMakeLists.txt, misc/script/linglong-repair-tool, misc/share/applications/linglong-repair-tool.desktop, rpm/linglong.spec
=> fix: move the reinstall operation to new script

debian/linglong-bin.preinst
Get list from directory instead of ll-cli list.
Log:
=> fix: use another way to get old package list

debian/changelog
=> chore: release linglong 1.5.1

apps/ll-box/src/container/mount/host_mount.cpp
=> build: add missing header

libs/linglong/src/linglong/cli/cli.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/8580
=> fix: add uid and gid to extra exec option and correct commands

libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/builder/source_fetcher.cpp, libs/linglong/src/linglong/builder/source_fetcher.h
=> refactor: make cacheDir to be the member of SourceFetcher

CMakeLists.txt
修改项目的版本
Log: update project version
=> feat: update project version

apps/generators/90-legacy/src/main.cpp, libs/linglong/src/linglong/runtime/container.cpp
/etc/resolv.conf must be mount to container
Log:
=> fix: linglong app can not access network

apps/ll-box/src/container/helper.cpp, apps/ll-box/src/main.cpp
=> refactor(ll-box): arguments parsing

.reuse/dep5, apps/ll-builder/src/main.cpp, misc/linglong/builder/templates/example.yaml
Generate linglong.yaml from example.yaml.
Log:
=> refactor: ll-builder create

apps/ll-box/src/main.cpp
=> fix: couldn't find binary in container

libs/linglong/src/linglong/builder/linglong_builder.cpp
=> fix: print develop module when pulling runtime

docs/pages/en/guide/ll-pica/adep.md, docs/pages/guide/ll-pica/adep.md
=> fix: fix docs

apps/generators/30-user-home/src/main.cpp
=> feat: mount default bashrc into container

apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp
ll-builder run添加offline参数,便于测试本地的Runtime
Log:
=> feat: add offline parameter to ll-builder run

misc/libexec/linglong/upgrade-all
=> fix: org.deepin.foundation won't be upgrade by timer

docs/pages/guide/debug/faq.md
=> fix: typos in the FAQ

libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp
https://github.com/linuxdeepin/linglong/issues/470
https://github.com/linuxdeepin/linglong/issues/462
Log:
=> fix: remove extra dir after uninstall & no package exist after update failed 

misc/share/linglong/builder/templates/example.yaml
=> chore: fix example.yaml spell

apps/ll-builder/src/main.cpp
ll-builder添加-f参数用于手动选择非当前目录下的linglong.yaml
Log:
=> feat: ll-builder allows manual linglong.yaml selection

libs/linglong/src/linglong/repo/ostree_repo.cpp
ostree拉取数据时不再使用临时仓库, 这样在网络中断后可以续传
Log:
=> feat: does not use temporary repository when pulling

libs/linglong/src/linglong/package_manager/package_manager.cpp
=> chore: add const to ref in Update() and print ref value

apps/ll-builder/src/main.cpp, apps/ll-cli/src/main.cpp, apps/ll-package-manager/src/main.cpp, libs/linglong/CMakeLists.txt, libs/linglong/src/linglong/repo/client_factory.cpp, libs/linglong/src/linglong/repo/client_factory.h, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h
使用单独的client发送http请求, 避免请求结果混淆
Log:
=> feat: Create dedicated client for HTTP requests

libs/linglong/src/linglong/repo/client_factory.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp
=> fix: dangling pointer issue by retaining shared_ptr

apps/ll-box/src/main.cpp, debian/changelog, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/runtime/container.cpp
This reverts commit f88b81dc8e5387c55dc77740f1833ea62f7f9573, and release 1.5.5.
=> Release 1.5.5

apps/ll-builder/src/main.cpp
在构建应用时,如果版本号不符合规范会在最后的commit阶段报错
应该提前检查yaml文件是否符合规范
Log:
=> feat: Check the version number in advance

.reuse/dep5, debian/linglong-bin.install, misc/CMakeLists.txt, misc/lib/systemd/system/org.deepin.linglong.PackageManager.service, misc/share/polkit-1/actions/org.deepin.linglong.PackageManager.policy, rpm/linglong.spec
org.deepin.linglong.PackageManager add Capability_Check, Cgroup_Check and Polkit_Check
Log:
=> feat: org.deepin.linglong.PackageManager add security check

apps/ll-box/src/container/container.cpp
if someting goes wrong, return early and create ll-host under tmpfs
=> refactor: checking some operations of ll-box are exectuing successfully or not

CMakePresets.json
Remove address sanitize as it conflicts with static build
=> build: update preset

CMakeLists.txt, apps/generators/25-host-env/CMakeLists.txt, apps/generators/25-host-env/src/main.cpp, debian/linglong-bin.install, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/runtime/container.cpp, misc/CMakeLists.txt, misc/lib/linglong/container/config.d/25-host-env, rpm/linglong.spec
Add new generator 25-host-env and use it.
Log:
=> refactor: add 25-host-env to generate env variables

debian/rules
debian rules install path error
Log:
=> chore: debian rules install path error

libs/linglong/src/linglong/runtime/container.cpp
We should append the process.env which from Container::run to the origin container config.
Log:
=> fix: missed some env during ll-builer build

misc/share/bash-completion/completions/ll-cli
Support completion of install layer file.
Log:"
=> chore: update bash completion of ll-cli

debian/changelog
release 1.5.6-1
Log: bump version to 1.5.6-1
=> chore: bump version to 1.5.6-1

misc/share/bash-completion/completions/ll-cli
fix https://github.com/linuxdeepin/developer-center/issues/9382
Log:
=> fix: update bash completion

apps/ll-session-helper/src/main.cpp, rpm/linglong.spec
给 rpm 打包安装 ll-session-helper
Log: install for rpm
=> chore: install for rpm

libs/linglong/src/linglong/repo/ostree_repo.cpp
=> fix: ll-cli abort after construct OSTreeRepo

api/schema/v1.json, api/schema/v1.yaml, libs/api/src/linglong/api/types/v1/Generators.hpp, libs/api/src/linglong/api/types/v1/Info.hpp, libs/api/src/linglong/api/types/v1/UabLayer.hpp, libs/linglong/CMakeLists.txt, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/package/layer_dir.cpp, libs/linglong/src/linglong/package/layer_dir.h, libs/linglong/src/linglong/package/uab_file.cpp, libs/linglong/src/linglong/package/uab_file.h, libs/linglong/src/linglong/package/uab_packager.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_manager.h, libs/linglong/src/linglong/package_manager/task.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h, libs/utils/src/linglong/utils/packageinfo_handler.cpp, libs/utils/src/linglong/utils/packageinfo_handler.h, libs/utils/src/linglong/utils/serialize/json.h
linglong doesn't have a completed mechanism of minifying dependencies yet, it will be implemented later
=> feat: support for installing from uab

libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h
prune本身执行比较耗时, 会影响各种操作的速度
在后续挑选合适的时机进行prune
Log:
=> feat: Do not prune when deleting refs

misc/lib/linglong/container/config.json
=> fix: hooks missing command args

debian/rules
should use OS_VERSION rather than VERSION
LOG:
=> fix: ENABLE_STATIC_BOX not enable

apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/package/architecture.cpp, libs/linglong/src/linglong/package/architecture.h, libs/linglong/src/linglong/package/fuzzy_reference.cpp, libs/linglong/src/linglong/package/reference.cpp, libs/linglong/src/linglong/package/uab_packager.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/runtime/container.cpp
=> feat: support loong64 arch

libs/linglong/src/linglong/cli/printer.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/10430
=> fix: improve `ll-cli ps` output

docs/pages/en/guide/start/install.md, docs/pages/guide/start/install.md
Import gpg public key before install.
Log:
=> chore: update install.md

api/schema/v1.json, api/schema/v1.yaml, libs/api/src/linglong/api/types/v1/Generators.hpp, libs/api/src/linglong/api/types/v1/RepositoryCacheLayersItem.hpp
Booking the commit hash of base and runtime in object which depends by current item.
Adding these properties for the 'minified' feature of UAB
=> feat: changing the api 'RepositoryCacheLayersItem'

libs/linglong/CMakeLists.txt, libs/linglong/src/linglong/repo/repo_cache.cpp, libs/linglong/src/linglong/repo/repo_cache.h
This class will be a member of OSTreeRepo.
Log:
=> feat: add class RepoCache

libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h, libs/linglong/src/linglong/repo/repo_cache.cpp, libs/linglong/src/linglong/repo/repo_cache.h
=> feat: add cache to OSTreeRepo

libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/repo_cache.cpp, libs/linglong/src/linglong/repo/repo_cache.h
* Using new flag OSTREE_REPO_PULL_FLAGS_NONE. (pull)
* Using layer info which from cache. (listLocal)
* Get repo name from ref. (rebuildCache)
* Return with no error. (searchLayerItem)
* If cacheRef.id is empty, return all items. (searchLayerItem)
Log:
=> refactor: modify pull/listLocal/rebuildCache/searchLayerItem

apps/ll-cli/src/main.cpp
Wait for the migration to complete, maybe ll-package-manager is busy now.
Log:
=> feat(ll-cli): call WaitForAvailable before init PackageManager

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/repo_cache.cpp, libs/utils/src/linglong/utils/packageinfo_handler.cpp
=> fix: some errors during migration

CMakeLists.txt
update CMakeList version to 1.6.1
Log:
=> chore: update CMakeList

libs/linglong/src/linglong/package/reference.cpp, libs/linglong/src/linglong/package/reference.h
=> feat: add some serialization func to reference

libs/linglong/src/linglong/builder/linglong_builder.cpp
在加了LINGLONG_DEBUG环境变量时, 不再使用base64编码容器ID, 避免调试困难
Log:
=> feat: Do not base64 encode container id when debugging

apps/ll-box/src/container/mount/host_mount.cpp
When we lookup the source of a mount, unless we get a mount option tell
us to not follow symbol link, which means to treat the link it self as
a regular file, we should always follow the link.
For example, if the /etc in runtime namespace is a symbol link to
/usr/etc, and config.json tell us to perform a bind mount from runtime
namespace /etc to container namespace /etc, then the old code will
create /etc in container namespace as a file, which leads to an ENOTDIR
error when doing the bind mount.
Bug: https://pms.uniontech.com/bug-view-274969.html
=> fix(box): default to follow symbol link when parse mount source

libs/linglong/src/linglong/repo/ostree_repo.cpp
Only export specified directorys, prevent files installed by applications from affecting the operation of the host system. specified directorys reference: https://github.com/flatpak/flatpak/blob/79abc960a6d695af3928aa7c5ca34b059e0d55f5/app/flatpak-builtins-build-finish.c#L233
Log: linglong export reference optimization
=> feat: optimization reference export

libs/linglong/src/linglong/package_manager/package_manager.cpp
Should update task context to installing status before pull runtime or base.
Log: fix update task context status abnormal
=> fix(package_manager): adjust update task context status

docs/pages/en/guide/ll-pica/convert-flatpak.md, docs/pages/guide/ll-pica/convert-flatpak.md
Update the documentation for converting Flatpak applications to Linglong applications.
Log: update docs
=> docs: update docs

docs/pages/en/guide/ll-builder/manifests.md, docs/pages/en/guide/start/how_to_use.md, docs/pages/guide/ll-builder/manifests.md, docs/pages/guide/start/how_to_use.md
Fix org.deepin.calculator example error
Log: update docs
=> docs: fix example error

api/dbus/org.deepin.linglong.PackageManager1.xml, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/json_printer.cpp, libs/linglong/src/linglong/cli/json_printer.h, libs/linglong/src/linglong/cli/printer.cpp, libs/linglong/src/linglong/cli/printer.h, libs/linglong/src/linglong/package/reference.cpp, libs/linglong/src/linglong/package/reference.h, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_manager.h
* Implement Prune in package_manager.cpp.
* Overload the less-than operator of reference.
Log:
=> feat: support prune

misc/share/mime/packages/vnd.linyaps.uab.xml
Optimization uab mime config file,
refer to: https://specifications.freedesktop.org/shared-mime-info-spec/latest/ar01s02.html.
=> refactor(config): optimization uab mime config

libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/package_manager/package_task.h
GCC version: 8.3.0
Qt version 5.11.3
=> fix: failure to compile under older versions of GCC and Qt

apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp
修复因命令行解析配置错误导致无法推送单个模块
修复混用new和free
修复source没有url时报错信息不明
改进debug参数的说明
在pull依赖后应该执行一次模块合并操作
=> fix: unable to push a single module

libs/linglong/src/linglong/package_manager/package_manager.cpp
=> fix: not comparing the arch during install layer/uab

debian/changelog
release 1.6.3-1
Log: bump version to 1.6.3-1
=> chore: bump version to 1.6.3-1

libs/linglong/src/linglong/cli/printer.cpp, libs/linglong/src/linglong/package_manager/package_task.cpp, libs/linglong/src/linglong/package_manager/package_task.h, libs/linglong/src/linglong/repo/repo_cache.cpp, libs/linglong/src/linglong/repo/repo_cache.h
*Print '/n' after the substate is Done.
*Add a variable to store the version of state.json.
*Remove unused func setProPerty().
Log:
=> fix: minor errors after refactor

libs/linglong/src/linglong/package_manager/package_manager.cpp
The value should be determined directly instead of using Q_ASSERT.
=> fix(package_manager): error to use Q_ASSERT

libs/linglong/src/linglong/package/reference.h, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_task.cpp
=> fix: coredump and abnormal registration of dbus

libs/linglong/src/linglong/repo/ostree_repo.cpp
在查询merged目录的文件列表时没有考虑目录不存在的情况
再加上没有捕获std::filesystem的错误返回值, 导致合并模块时会抛出异常
=> fix: exception thrown when merging modules

api/dbus/org.deepin.linglong.PackageManager1.xml, api/schema/v1.json, api/schema/v1.yaml, apps/ll-builder/src/main.cpp, apps/ll-cli/src/main.cpp, libs/api/src/linglong/api/types/v1/CommonResult.hpp, libs/api/src/linglong/api/types/v1/Generators.hpp, libs/api/src/linglong/api/types/v1/LinglongAPIV1.hpp, libs/api/src/linglong/api/types/v1/PackageManager1GetRepoInfoResult.hpp, libs/api/src/linglong/api/types/v1/PackageManager1JobInfo.hpp, libs/api/src/linglong/api/types/v1/PackageManager1PackageTaskResult.hpp, libs/api/src/linglong/api/types/v1/PackageManager1RequestInteractionAdditionalMessage.hpp, libs/api/src/linglong/api/types/v1/PackageManager1SearchResult.hpp, libs/api/src/linglong/api/types/v1/SubState.hpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/cli/printer.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_manager.h, libs/linglong/src/linglong/package_manager/package_task.cpp, libs/linglong/src/linglong/package_manager/package_task.h, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h, libs/linglong/src/linglong/repo/repo_cache.cpp, libs/linglong/src/linglong/repo/repo_cache.h
fix some errors which have been found while testing
=> feat:  implement the 'deferred uninstallation' feature

libs/linglong/src/linglong/builder/linglong_builder.cpp
Only install specified share directorys in build.
Log: ll-builder add filter entries share dir
=> refactor(ll-builder): ll-builder filter entries share dir

libs/linglong/CMakeLists.txt, libs/linglong/src/linglong/cli/cli.cpp
=> fix: typo and duplicated code in CMakeList.txt

libs/linglong/src/linglong/cli/cli.cpp
Json can not has std::cout output, it only output in ssh.
=> fix(cli): ll-cli --upgradable error to output standard output stream

CMakeLists.txt, apps/ll-cli/CMakeLists.txt, misc/share/polkit-1/actions/org.deepin.linglong.PackageManager1.policy
=> fix: auth_admin_keep is not worked

apps/ll-cli/src/main.cpp
Do not use '\n' in command description, or it will show abnormal.
=> fix(cli): cli command output show abnormal

api/schema/v1.yaml
Add compatible_version to record linyaps package is compatible with linyaps component version.
=> feat: info.json add compatible_version option

api/schema/v1.json, api/schema/v1.yaml, docs/pages/guide/ll-builder/modules.md, libs/api/src/linglong/api/types/v1/BuilderProjectModules.hpp, libs/api/src/linglong/api/types/v1/Generators.hpp, libs/api/src/linglong/api/types/v1/PackageInfoV2.hpp, libs/linglong/src/linglong/builder/linglong_builder.cpp
files从字符串改为字符串数组, 不再需要切分, 避免yaml格式化导致切分错误
当没有配置develop模块并未开启full develop选项, develop使用内置默认值
=> feat: modules.files type changed from string to array

misc/share/bash-completion/completions/ll-builder, misc/share/bash-completion/completions/ll-cli
Both of ll-cli and ll-builder.
Log:
=> fix: broken bash completions

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli.cpp, misc/share/dbus-1/system.d/org.deepin.linglong.PackageManager1.conf
* Not doing interact before migration, only notification.
* Allow anyone to call WaitForAvailable() by dbus.
Log:
=> fix: no permission to migrate

apps/ll-cli/src/main.cpp
=> fix(ll-cli): used a moved object

libs/linglong/src/linglong/cli/cli.cpp
* Used a std::optional variable without check value.
* Should return after exiting the QEventLoop.
* Check the result code before use it.
Log:
=> fix: coredump during ll-cli search failed

.reuse/dep5, CMakeLists.txt, LICENSES/GPL-2.0-or-later.txt, apps/ll-cli/src/main.cpp, debian/linglong-bin.install, libs/utils/CMakeLists.txt, libs/utils/src/linglong/utils/configure.h.in, libs/utils/src/linglong/utils/gettext.h, po/CMakeLists.txt, po/LINGUAS, po/POTFILES.in, po/en_GB.po, po/en_US.po, po/es.po, po/linyaps.pot, po/zh_CN.po, rpm/linglong.spec
Add ll-cli chinese and spanish help information.
=> feat(cli): linglong cli help information internationalization

tools/test-linglong.sh
Add script to test the basic functions of ll -cl i
Log: add test script
=> feat: add test script for ll-cli

libs/linglong/src/linglong/repo/ostree_repo.cpp, misc/share/bash-completion/completions/ll-cli
* bash-completion error in 'll-cli search';
* upgrade failed when the local app's module is runtime;
=> fix: bash-completion error & upgrade failed

libs/linglong/src/linglong/cli/cli.cpp
在安装时会使用pkexec提权, pkexec默认不继承当前的工作目录和环境变量
所以使用--keep-cwd参数让pkexec继承工作目录
因为环境变量也不会继承, 并且没有需要继承环境的场景,不再传递当前环境变量给pkexec
=> fix: ll-cli cannot install layer and uab files

api/schema/v1.json, api/schema/v1.yaml, libs/api/src/linglong/api/types/v1/Generators.hpp, libs/api/src/linglong/api/types/v1/State.hpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/cli/cli_printer.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_manager.h, libs/linglong/src/linglong/package_manager/package_task.cpp, libs/linglong/src/linglong/package_manager/package_task.h, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h
=> refactor: adjust the behavior of ll-cli upgrade

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli.cpp
Fallback to DummyNotifier if no avilable notifier.
Log:
=> fix: cli returned if no avilable notifier

libs/linglong/src/linglong/repo/ostree_repo.cpp
std::filesystem::exist will follow symlink
=> fix: use symlink_status to check symlink exist or not

libs/linglong/src/linglong/repo/ostree_repo.cpp
The module which is a paramater in pull could be runtime, it cause the fallback mechanism not work.
Log:
=> fix: upgrade failed from oldRef/runtime to newRef/runtime

debian/control, debian/linglong-bin.install
Add intltool to build depends.
=> fix: intltool-update can not found

apps/ll-cli/src/main.cpp
Cli version add json format output.
=> feat(cli): cli version support json format output

libs/linglong/src/linglong/repo/ostree_repo.cpp
compare refs before commit to ostree
=> fix: add more check while migrating

libs/linglong/src/linglong/builder/linglong_builder.cpp
临时创建的mergedDir被mergeModules函数清理了,
现在在mergeModules之后创建mergedDir
=> fix: ll-builder cannot run the application with debug

libs/linglong/src/linglong/package_manager/package_task.cpp
=> fix: progress overflow during upgrade all

libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli_printer.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp
* Return after ret with error.
* Call the prune of ostree after remove unused runtime or base.
Log:
=> fix: some minor issues

apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp
现在develop会自动构建, 在push的时候也应该自动推送
=> feat: auth push the develop module

apps/generators/30-user-home/src/main.cpp
std::exist will follow symlink
so we should get status at first
=> refactor(gen): add blackList for hide some directory all the time

libs/linglong/src/linglong/repo/ostree_repo.cpp
If the reason is not "No such branch ...", do not fallback.
Log:
=> fix: return wrong state during pull

libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/package_manager/package_task.cpp, libs/linglong/src/linglong/package_manager/package_task.h, libs/linglong/src/linglong/repo/ostree_repo.cpp
=> fix(ll-builder): broken progress display during pull

apps/ll-builder/src/main.cpp
Use BuilderBuildOptions to replace variable directly.
=> refactor(ll-build): use build optios to replace variable

libs/linglong/src/linglong/builder/linglong_builder.cpp
优化生成gdbinit的代码, 使逻辑更清晰
debug-file-directory使用绝对路径而不是substitute-path二次转换, 避免低版本gdb不支持
=> feat: optimize gdbinit

libs/linglong/src/linglong/cli/cli.cpp
Issue: https://pms.uniontech.com/bug-view-283279.html
=> fix: resolve symlink in filepathMapping

libs/linglong/src/linglong/cli/cli.cpp
=> fix: crashed in anolisos 23.1 after ll-cli run

libs/linglong/src/linglong/cli/cli.cpp
Return early if the current user is root.
Log:
=> fix(cli): refuse to run application as root

libs/linglong/src/linglong/cli/cli.cpp
Adjust the log output level to debug, do not show extra information.
=> fix(cli): cli list --upgradable show extra information

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, po/en_GB.po, po/en_US.po, po/es.po, po/linyaps.pot, po/zh_CN.po
Support kill or enter application by appid.
=> feat(cli): support kill or enter container by appid

apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/builder/linglong_builder.h, po/en_GB.po, po/en_US.po, po/es.po, po/linyaps.pot, po/zh_CN.po
builder添加应用列表和删除应用的命令, 便于开发者清理构建缓存
=> feat: add list and remove commands to builder

apps/ll-box/src/container/container.cpp, apps/ll-box/src/container/container.h, apps/ll-box/src/container/helper.cpp, apps/ll-box/src/container/helper.h, apps/ll-box/src/main.cpp
refactor the way of parsing and executing command
now parsing all args at first
=> feat(ll-box): support global option 'root'

CMakeLists.txt, apps/ll-box/src/container/helper.h, apps/uab/header/CMakeLists.txt, apps/uab/header/src/main.cpp, libs/linglong/tests/ll-tests/CMakeLists.txt, libs/linglong/tests/ll-tests/src/linglong/utils/xdg/desktop_entry_test.cpp
and fix some errors.
more detials refer to commits
=> refactor(uab): remove openssl

external/http/include/apiClient.h, external/http/src/apiClient.c, libs/linglong/src/linglong/repo/client_factory.cpp, libs/linglong/src/linglong/repo/client_factory.h, libs/linglong/src/linglong/repo/ostree_repo.cpp, tools/openapi-c-libcurl-client/apiClient.c.mustache, tools/openapi-c-libcurl-client/apiClient.h.mustache
=> feat: custom user-agent with api client and ostree

libs/linglong/src/linglong/repo/repo_cache.cpp
=> fix: the permission of states.json is incorrect

libs/linglong/src/linglong/package_manager/package_manager.cpp
=> fix: optimize the downgrade prompt output during install

libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_manager.h
=> fix: add task execution log & fix the crashed issue of PM

api/dbus/org.deepin.linglong.PackageManager1.xml, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_manager.h
* fix: unused base or runtime will be removed after install/uninstall/update
* fix: cli print invalid task when the task is queued
* fix: the canceled task would be set to Queued again
=> fix: some important issues

apps/uab/header/CMakeLists.txt, apps/uab/header/src/light_elf.h, apps/uab/header/src/main.cpp, apps/uab/header/src/utils.h
implement needed functions in light_elf
=> refactor(uab): remove dependency 'libelf'

libs/linglong/src/linglong/builder/linglong_builder.cpp
旧版本玲珑不支持遍历entries/share目录中的软链接, 为保持兼容,
构建应用后不在entries/share目录创建软链接, 而是复制文件
=> fix: old version of ll-cli cannot export the new package

apps/generators/90-legacy/src/main.cpp
dtk的关于对话框中显示的网址信息是从系统文件中读取的,
需要将宿主机的文件挂载到容器中, 才能正常显示
Bug: https://pms.uniontech.com/bug-view-282565.html
=> fix: incorrect official website display in the DTK About dialog

libs/linglong/src/linglong/package_manager/package_manager.cpp
Set the runningTaskObjectPath before the next available task start instead of after the last task finished.
Log:
=> fix: PM blocked in a cancled task

libs/linglong/src/linglong/runtime/container_builder.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/30_user_home.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/90_legacy.cpp
Signed-off-by: ComixHe <heyuming@deepin.org>
=> fix: skip some generating steps which related to env 'HOME'

libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_task.h
The job which the state is not Queued or has no job should be remove.
Log:
=> fix: install app failed after it was cancled before

.obs/workflows.yml
使用link_package会为每个commit创建包, 太占用存储空间, 仅保留最新一个即可
=> feat: update obs workflows

docs/pages/en/guide/debug/faq.md, docs/pages/guide/debug/faq.md
Add about the issue of not displaying the app tray after app startup
Log: add faq
=> chore: add faq

tools/test-linglong.sh
Update the test script, remove sudo authentication, and run it locally to pop up an authentication box
Log: update test script
=> chore: update test-linglong.sh

libs/linglong/src/linglong/repo/ostree_repo.cpp
=> fix: getOriginRawExec which in ostree.cpp  occurs error

libs/linglong/src/linglong/package_manager/package_task.h
Allow setup different tasks by the same ref.
=> fix: can not install app when cancel a task

apps/ll-package-manager/src/main.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h
1. we must fix export entries when in no dbus mode;
2. we must copy application entries directorys to the root entries directorys before rewrite file;
=> fix: error to export applications entries directory

po/zh_CN.po
=> fix: translation error

libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/runtime/container_builder.cpp, libs/linglong/src/linglong/runtime/container_builder.h
we need and only need to generate and mount zz_deepin-linglong-app.conf during generating ld cache
=> fix: adjust generating ld.so.cache

libs/linglong/src/linglong/repo/ostree_repo.cpp
Root entries directory should be symlink, or it can not be remove when uninstall app. so we can not copy file to root entries directory but copy file in app entries and then modify.
=> fix: launcher icon displays abnormally after uninstalling the app

libs/linglong/src/linglong/package/architecture.cpp, libs/linglong/src/linglong/package/architecture.h
=> feat: add sw arch support

apps/uab/header/src/main.cpp, libs/linglong/src/linglong/package/uab_packager.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/25_host_env.cpp
修复导出uab报错无效的跨设备链接
修复config.yaml的alias为空时会crash
https://github.com/OpenAtom-Linyaps/linyaps/issues/811
=> fix: resolve "Invalid cross-device link" error during UAB export

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli_printer.cpp, po/POTFILES.in, po/en_GB.po, po/en_US.po, po/es.po, po/linyaps.pot, po/zh_CN.po
Adjust the uppercase of the output Title.
=> chore: output Title in uppercase

libs/linglong/src/linglong/cli/cli_printer.cpp
Unable to calculate the maximum width for each column because some appid and appname are too long, which would cause output to be messy.
=> fix: search results show confusion

libs/linglong/src/linglong/package/architecture.cpp, libs/linglong/src/linglong/package/architecture.h
=> feat: add mips64 arch

po/en_GB.po, po/en_US.po, po/es.po, po/linyaps.pot, po/zh_CN.po
=> chore: update translate

libs/oci-cfg-generators/src/linglong/oci-cfg-generators/20_devices.cpp
/media is symlink(/run/media) in v25, app can not access the dir so we should mount /media, /run/media to container and keep symlink.
=> fix: can not save file to media

debian/linglong-bin.install, misc/CMakeLists.txt, misc/share/zsh/vendor-completions/_ll-cli, rpm/linglong.spec
ll-cli in zsh supports automatic completion.
=> feat: add command automatic completion for zsh

misc/share/mime/packages/vnd.linyaps.uab.xml
Update generic-icon to universal-application-bundle.
=> fix: uab icon display abnormality

libs/linglong/tests/ll-tests/CMakeLists.txt, libs/linglong/tests/ll-tests/src/linglong/repo/config_test.cpp
test getRepoMinPriority
test getRepoMaxPriority
test convertToV2
=> test: add unit test for repo config

apps/ll-box/src/main.cpp, apps/ll-box/src/util/filesystem.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/builder/printer.h, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp
=> chore: fix some compile warning

libs/linglong/src/linglong/repo/ostree_repo.cpp
Parameter("-- --") parsing error when exec not have field codes.
=> fix: app can not start by laucher

libs/linglong/src/linglong/cli/cli.cpp
Fix some applications can't write to files or delete files under home directory
=> fix: Dont't mapping the file under /home

libs/linglong/src/linglong/builder/linglong_builder.cpp
构建工具未使用linglong.yaml的channel字段
Log:
=> fix: builder does not use the channel field of linglong.yaml

libs/linglong/src/linglong/package/uab_packager.cpp
=> fix: Fix export empty app layer

libs/linglong/src/linglong/cli/cli_printer.cpp
Optimize ps and list --upgrade's output.
翻译后面单独补充吧
=> feat: optimizing cli output

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h
ll-cli add dir sub command to support get layer director by appid.
=> feat(cli): ll-cli add dir sub command

libs/linglong/src/linglong/cli/cli.cpp
Fix upgrade progress will exceed 100%.
=> fix: upgrade progress abnormal

libs/linglong/src/linglong/runtime/container.cpp
Merge environment variable if possible
=> fix: fix missing environment variable

libs/linglong/src/linglong/cli/cli.cpp
fix an unintentional change made by commit d7cea3443aa8afbbb88e6d106461e55f29925a07
=> fix: fix mapping file

REUSE.toml, misc/CMakeLists.txt, misc/share/applications/linyaps.desktop
Add linglong desktop file to support install uab.
=> feat: add linglong desktop

BUILD.md, BUILD.zh_CN.md, misc/share/bash-completion/completions/ll-cli
=> chore: update bash-completion

libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/25_host_env.cpp
Support export dsg config file for self-developed applications.
=> feat: support export dsg config file

libs/linglong/src/linglong/repo/ostree_repo.cpp
Delete empty directories after uninstalling the app.
=> fix: empty directory exists after app uninstall

release.bash
=> feat: add release script

misc/lib/linglong/container/config.d/10-basics.json
在之前的提交中, 本应删除/tmp挂载, 却误删了/dev的挂载
=> fix: adjust container mount items

apps/ll-builder/src/main.cpp
tryMigrate may use ostree repo, put GIO_USE_VFS=local before it
=> fix: fix unshare error

libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp
Templates file should be exported, add it to whitelist.
=> feat: add share/templates dir to whitelist

CMakeLists.txt, libs/dbus-api/CMakeLists.txt, libs/linglong/CMakeLists.txt
Support Qt6 packaging according to the method recommended by the Qt official.
=> feat: support Qt6 packaging

apps/ll-builder/src/main.cpp
set GVFS_REMOTE_VOLUME_MONITOR_IGNORE to 1
=> fix: avoid gio start thread before unshare

.tx/transifex.yaml
=> chore: add transifex config file

apps/ll-builder/src/main.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/builder/linglong_builder.h, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp
1. use project directory
2. bind host statics in build
=> Fix builder

api/dbus/org.deepin.linglong.PackageManager1.xml, api/dbus/org.deepin.linglong.Task1.xml, apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/cli/cli_printer.cpp, libs/linglong/src/linglong/cli/cli_printer.h, libs/linglong/src/linglong/cli/json_printer.h, libs/linglong/src/linglong/cli/printer.h, libs/linglong/src/linglong/package/fuzzy_reference.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/package_manager/package_manager.h, libs/linglong/src/linglong/package_manager/package_task.cpp, libs/linglong/src/linglong/package_manager/package_task.h, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/utils/src/linglong/utils/error/error.h
Define error codes to identify different errors.
The cli displays error information to users based on error codes.
Add -v,--verbose option to display detailed error information.
=> feat: Optimization error message

README.zh_CN.md
- 扩展项目亮点、安装说明和动机等内容。
- 增加性能对比和详细的文档链接。
- 新增社区参与和贡献指南。
- 更新许可证信息和相关项目参考。
=> docs: 更新 README.zh_CN.md，增强项目信息和可访问性

README.md
- Expand project highlights, installation instructions, motivations, etc.
- Add performance comparisons and detailed documentation links.
- Add community participation and contribution guidelines.
- Update license information and related project references.
=> docs: Update README.md to enhance project information and accessibility

docs/pages/en/guide/ll-builder/export.md, docs/pages/en/guide/ll-builder/manifests.md, docs/pages/guide/ll-builder/export.md, docs/pages/guide/ll-builder/manifests.md
Update ll-builder documentation
=> docs: Update ll-builder export documentation

libs/api/src/linglong/api/types/helper.h
之前添加优先级配置的时候，忘了修改重载的函数，导致修改无法写入到配置文件里
=> fix: cannot set priority

libs/oci-cfg-generators/src/linglong/oci-cfg-generators/20_devices.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/40_host_ipc.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp
'nosymfollow' doesn't satisfying with our purpose
=> fix: remove option 'nosymfollow'

docs/pages/en/guide/ll-pica/install.md, docs/pages/en/guide/start/install.md, docs/pages/guide/ll-pica/install.md, docs/pages/guide/start/install.md
=> docs: update install docs

libs/linglong/src/linglong/package/uab_packager.cpp
=> fix: build error in ci build

libs/linglong/src/linglong/cli/cli.cpp
Update URL prefix to use Correct file path.
=> fix: app can not open url

apps/ll-builder/src/main.cpp, libs/linglong/tests/ll-tests/src/linglong/package/semver_increment_test.cpp
1. improve base and runtime version validation
2. format semver_increment_test.cpp
=> fix: improve base and runtime version validation

libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli_printer.cpp
Enhance CLI repository information display with dynamic column widths and URL truncation:
1. Calculate maximum lengths for name, URL, and alias columns dynamically
2. Limit URL display length to 100 characters with ellipsis for longer URLs
3. Use calculated widths instead of fixed column widths for better alignment
4. Truncate long URLs with "..." to improve readability
style: 改进仓库信息显示格式
增强命令行界面仓库信息显示，使用动态列宽和 URL 截断：
1. 动态计算名称、URL 和别名列的最大长度
2. 限制 URL 显示长度为 100 个字符，超长时添加省略号
3. 使用计算出的宽度而非固定列宽，以获得更好的对齐效果
4. 为长 URL 添加"..."截断，提高可读性
----
refactor: simplify repository priority management
1. Remove automatic priority calculation when adding new repos
2. Remove automatic priority adjustment when setting default repo
3. Allow multiple repositories to have the same priority value
4. Use stable sort …
=> style: improve repository information display formatting

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h
The default display type is changed from app to all.
=> refactor: adjust the default display type

libs/linglong/src/linglong/package_manager/package_manager.cpp
=> refactor: search no longer supports specifying a version

libs/linglong/src/linglong/cli/cli_printer.cpp, libs/linglong/src/linglong/cli/cli_printer.h, libs/linglong/src/linglong/cli/json_printer.cpp, libs/linglong/src/linglong/cli/json_printer.h, libs/linglong/src/linglong/cli/printer.h
Sort results of ll-cli search and list.
=> feat: sort search results

libs/oci-cfg-generators/src/linglong/oci-cfg-generators/20_devices.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/40_host_ipc.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/90_legacy.cpp
Improve error handling for filesystem existence checks.
=> fix: ll-cli failed to start app

libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.h
=> refactor: forwardEnv will forward all envs by default

libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.h
make basePath and bundlePath to be required field
=> refactor: add getBundlePath

docs/pages/guide/debug/debug.md
…sitory
Included detailed steps for accessing the container, locating the repository, and downloading the necessary debug symbol packages for system dependencies. This enhances the debugging process for applications relying on external libraries.
=> docs: add instructions for downloading debug symbols

libs/linglong/src/linglong/cli/cli.cpp
The set-default command ensures compatibility by setting the priority. However, its modification to the priority is unidirectional and one-time, subsequent set-priority invokes will not alter the default state.
=> fix: preserve set-default compatibility

libs/linglong/src/linglong/repo/ostree_repo.cpp
Updated the exportDir function to rename source files to include a ".linyaps.original" suffix if they are not already named as such, ensuring proper handling during the export process. This change prevents overwriting original files and maintains compatibility with existing export logic.
=> fix: handle renaming and copying of non-original linyaps files in exportDir

.github/workflows/build.yaml
=> feat: add GitHub Actions workflow for build process

apps/ll-init/src/ll-init.cpp
=> fix: compiling error at UOS 20 and anolisOS

libs/linglong/src/linglong/builder/linglong_builder.cpp
=> fix: copy hidden files

apps/dumb-init/src/dumb-init.c
The pts inside the current container are inherited from outside
=> fix: remove setsid from dumb-init

libs/linglong/src/linglong/repo/ostree_repo.cpp
为了兼容上个版本直接对source进行重写，这里需要判断原始文件的硬链接数
如果硬链接数为1，则说明原始文件重写过了，就跳过重写
因为多次重写会导致应用出问题
=> fix: skip rewrite for files with a single hard link

apps/ll-init/src/ll-init.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.h
all of the builder container shouldn't reuse container
=> feat: add signleMode for ll-init

.deepsource.toml, README.md, README.zh_CN.md
Adds a DeepSource configuration file for static analysis and includes a DeepSource badge in the README files to display the project's code quality status.
=> chore: adds DeepSource configuration and badge

.deepsource.toml, docs/pages/guide/lessons/build-offline-src.md
Removes the meta analyzer configuration from the DeepSource configuration file.
=> chore: removes meta analyzer configuration

.github/workflows/build.yaml, .github/workflows/codecov.yaml, tools/generate-coverage.sh
=> feat: add test coverage workflow

.github/workflows/build.yaml, .github/workflows/codecov.yaml
1. Added erofs-utils package to the list of dependencies in both build.yaml and codecov.yaml workflows
2. This package is required for EROFS filesystem support in the build process
3. Ensures consistent development environment across different workflows
chore: 添加 erofs-utils 到构建依赖项
1. 在 build.yaml 和 codecov.yaml 工作流中添加了 erofs-utils 包到依赖项 列表
2. 该包是构建过程中 EROFS 文件系统支持所必需的
3. 确保不同工作流之间开发环境的一致性
=> chore: add erofs-utils to build dependencies

.deepsource.toml
=> chore: update deepsource config

misc/share/applications/linyaps.desktop
This reverts commit c33cf2a3a8b50f906849f6fc5cbfa02e98eea0e5.
=> Revert "chore: hide linyaps desktop file"

CMakePresets.json, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/runtime/run_context.cpp
优化layer查找的逻辑, 优先从默认仓库搜索, 再从多仓库搜索, 最后再回退runtime搜索
补充部分代码的错误信息传递
=> feat: Optimize layer search logic

apps/ll-builder/src/command_options.h, apps/ll-builder/src/main.cpp, apps/uab/header/src/main.cpp, apps/uab/loader/src/main.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/builder/linglong_builder.h, libs/linglong/src/linglong/package/reference.cpp, libs/linglong/src/linglong/package/reference.h, libs/linglong/src/linglong/package/uab_packager.cpp, libs/linglong/src/linglong/package/uab_packager.h, libs/utils/src/linglong/utils/error/error.h, linglong.yaml
Add ability to export specific package references from repository using --ref and --modules parameters, without requiring complete project setup.
This mode is only for distributing.
=> feat: add '--ref' export option for exporting package

misc/libexec/linglong/builder/helper/ldd-check.sh
改进ldd依赖检查的错误处理机制, 通过收集所有缺失的依赖项来增强错误报告
=> feat: improve ldd dependency check with better error handling

apps/ll-init/src/ll-init.cpp
- Only forward signals from non-kernel sources in handle_sigevent
- Handle EINTR in epoll_wait loop to avoid premature exit on signal interruption
=> fix(ll-init): improve signal handling robustness
