OpenAtom-Linyaps/linyaps

- misc/dbus/org.deepin.linglong.PackageManager.conf
- misc/dbus/org.deepin.linglong.SystemHelper.conf
- misc/systemd/service/org.deepin.linglong.PackageManager.service.in
- misc/sysuser/linglong.conf
Close #27
"linglong" will be a frequently-used name of chinese. Let's back to
"deepin-linglong".
This commit partly revert 4be58ef48ba962a43bb4f35440fd55fa18749b3b.
> fix: linglong -> deepin-linglong

- misc/scripts/create-linglong-dirs.in
- src/package_manager/impl/package_manager.cpp
ll-cli repo modify breaks after ef2317f819b4ed23a3d7f18379d2fbcb59fbdc11
QFile will create e file if it doesn't exist, so I just remove the
check.
> fix: make ll-cli repo modify work again

- src/module/repo/ostree_repo.cpp
命令行多加了一个参数,ostree会返回空内容,无法正确获取本地最新分支
Log:
> fix: Unable to get the latest local ref

- src/builder/builder/builder_config.cpp
- src/builder/builder/builder_config.h
- src/builder/builder/depend_fetcher.cpp
- src/builder/main.cpp
> feat: builder add offline parameter

- src/builder/builder/linglong_builder.cpp
Add 'X-linglong=${appId}' to the desktop entry to indicate
that this is a linglong application.
Log:
> feat: add a section to the desktop entry

- debian/changelog
- Revert "fix: some parameter of exec parsing failed"
- chore: bump version to 1.3.6
- feat: add a section to the desktop entry
- fix: Unable to get the latest local ref
- feat: builder add offline parameter
- chore: bump version to 1.3.7
> blakc desk/bump version

- .gitignore
- apps/ll-cli/src/main.cpp
- debian/control
- external/qserializer/CMakeLists.txt
- external/qserializer/examples/dbus_message/api/dbus/io.github.black_desk.TestDBusServer.xml
- external/qserializer/examples/dbus_message/apps/server/src/qserializer/examples/dbus_message/Server.cpp
- external/qserializer/examples/dbus_message/apps/server/src/qserializer/examples/dbus_message/Server.h
- external/qserializer/libs/core/include/qserializer/core.h
- external/qserializer/libs/core/include/qserializer/detail/QSerializer.h
- external/qserializer/libs/dbus/include/qserializer/dbus.h
- external/qserializer/tests/src/qserializer/test_types/Book.h
- src/linglong/package_manager/package_manager.cpp
- src/linglong/repo/ostree_repohelper.cpp
- src/linglong/repo/repo_client.cpp
- src/linglong/repo/repo_client.h
- src/linglong/util/config/CMakeLists.txt
- src/linglong/util/config/config.cpp
- src/linglong/util/config/config.h
- src/linglong/util/config/repo.cpp
- src/linglong/util/config/repo.h
- src/linglong/util/file.cpp
- chore: update .gitignore
- refact: move ConfigInstance into namespace
- refact: rename protect marco
- refact: remove unused headers
- refact: remove unnecessary namespace
- refact: move linglong::{,util::}config
- refact: move linglong::config::Repo into single file
- chore: update qserializer to 0.3.0
- chore(debian): adjust depends
- fix(cli): correct the default repo name
- fix(pm): use ConfigInstance in getRepoInfo
- fix(pm): update repo::RepoClient::endpoint
- fix: correct findLinglongConfigPath
> fix use correct config file

- apps/ll-builder/src/main.cpp
Unify all `addOption()` and `addOptions()` in `ll-builder`.
> refact(builder): unify addOptions() in ll-builder

- src/linglong/runtime/app.cpp
After using ocppi, annotation is default to empty.
Old logical return after set "enable" to false
cause this object exists by not competed,
which leads to a ll-box crash.
> fix: do not create "dbusProxyInfo" if not enable

- .reuse/dep5
- debian/changelog
- debian/linglong-bin.install
- misc/CMakeLists.txt
- misc/dbus/org.deepin.linglong.AppManager.service.in
- misc/systemd/service/org.deepin.linglong.AppManager.service.in
We can use systemd to start AppManager.
This commit remove the old configure files of autostart AppManager.
> refactor: use systemd to start AppManager

- src/module/runtime/app.cpp
sometimes `XAUTHORITY` will in `/tmp`.
> fix: mount XAUTHORITY in the correct order

- src/module/runtime/app.cpp
Temporarily mount the host /tmp into the container
backport from dd39a06e03bd6d92e38b487d4a6016feaae9826a
> fix: some app failed shared data by /tmp

- src/linglong/repo/ostree_repo.h
Remove static from struct OstreeRepoDeleter.
Log:
> fix: build failed in ostree_repo.cpp

- src/linglong/utils/command/env.cpp
Add environment variable GNOME_DESKTOP_SESSION_ID into container, some applications rely on this variable to decide whether to use gsettings configuration. Such as chrome.
Log:"
> fix: some app failed to use gsettings

- src/linglong/utils/error/error.h
- feat: add LINGLONG_GERR for error from glib
> add LINGLONG_GERR

- src/linglong/repo/ostree_repo.cpp
can not return error when failed to handle for devel modules
> fix: ignore pull or checkout error for devel

- src/linglong/repo/ostree_repo.cpp
the reference argument lost member variables
> fix: select the broken argument

- src/linglong/builder/linglong_builder.cpp
can not checkout because of the argument ref without channel field
> fix: ref without channel

- src/linglong/package_manager/package_manager.cpp
> fix: use default channel `main` when uninstall

- debian/control
We don't use linglong-dbus-proxy form now.
Log:
> chore: repolaces and conflicts linglong-dbus-proxy

- src/linglong/package_manager/package_manager.cpp
If the url ends with '/', just remove it.
Log:
> fix: install app failed after modify url

- src/linglong/builder/project.cpp
we will get '\n' if add '|' to the end of a key in yaml file, just remove it.
Log:
> fix: build failed with autotools mode in sometime

- src/linglong/cli/cli.cpp
We should tell AM that the desktop files were changed after installation. When Am can listen for file changes, remove this code.
Log:
> fix: call ReloadApplications after installation

- src/linglong/builder/linglong_builder.cpp
- src/linglong/builder/linglong_builder.h
容器运行失败时应该返回错误
否则无法判断构建是否成功
Log:
> feat: Container failure should return an error

- apps/ll-builder/src/main.cpp
- src/linglong/builder/builder_config.cpp
buildArch默认使用主机的架构
修复builder run架构为空的问题
Log:
> feat: buildArch uses host arch by default

- src/linglong/runtime/app.cpp
- src/linglong/runtime/app.h
在运行应用时使用squash_to_uid参数挂载rootfs，避免权限问题
构建时因为应用文件存放在家目录,不会有权限问题,所以没加这个参数
Log:
> feat: mount rootfs using the 'squash_to_uid' args

- src/linglong/runtime/container_builder.cpp
修复执行patch脚本超时的问题
应该在将数据写入到标准输入后,关闭写流程序才会退出
Log:
> fix: exec patch script timeout

- src/linglong/utils/command/env.cpp
容器环境缺少XDG_RUNTIME_DIR环境变量
Log:
> fix: missing XDG_RUNTIME_DIR environnent variable

- src/linglong/runtime/container.cpp
禁用crun自己创建cgroup，便于AM识别管理应用
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/7780
> feat: crun disable cgroup manager

- src/linglong/builder/linglong_builder.cpp
- src/linglong/package_manager/task.cpp
- src/linglong/package_manager/task.h
- src/linglong/repo/ostree_repo.cpp
将临时仓库放到.cache目录避免checkout时文件复制
在设置临时仓库的父仓库后,重新打开仓库使配置生效,避免增量更新无法使用
Log:
> fix: optimizing pull method

- debian/rules
- debian/sysctl.d/linglong.conf
set kernel kernel.unprivileged_userns_clone opt when it not set and we must set it in uos 20 amd64 arch
Log:
> feat: set kernel kernel.unprivileged_userns_clone opt when it not set

- api/schema/v1.yaml
- apps/ll-builder/src/main.cpp
- src/linglong/api/types/v1/BuilderConfig.hpp
- src/linglong/api/types/v1/Generators.hpp
- src/linglong/builder/linglong_builder.cpp
- src/linglong/runtime/container_builder.cpp
build支持跳过拉取依赖的过程,便于在离线场景使用
Log:
> feat: ll-builder add the 'skip-pull-depend' param

- src/linglong/package/layer_file.cpp
- src/linglong/package/layer_packager.cpp
在导出Layer文件时, 应该强制使用小端编码, 避免兼容问题
Log:
> feat: QDataStream should be used with LittleEndian

- libs/linglong/src/linglong/package/layer_packager.cpp
pack should use LayerInfo instead of PackageInfo
Log:
> fix: ll-cli info show error

- apps/ll-box/src/container/container.cpp
- apps/ll-box/src/container/mount/host_mount.cpp
- apps/ll-box/src/util/oci_runtime.h
- libs/linglong/src/linglong/runtime/container.cpp
- **refact: archieve linglong runtime dir instead of leave it alone**
- **feat: support startContainer**
- **fix: correct second clone id mapping**
- **fix: correct hook exec**
- **fix: void use after move**
- **chore: remove a debug log**
> fix some bug in ll-box

- libs/linglong/src/linglong/builder/linglong_builder.cpp
The default module of org.deepin.foundation should be runtime.
Log:
> fix: ll-builder run failed

- debian/linglong-bin.postinst
linglong.conf should be reload after install
Log:
> fix: kernel.unprivileged_userns_clone not set in uos v20

- debian/rules
should use os-release to distinguish distro
Log:
> fix: linglong.conf not installed correctly in uos v20

- apps/ll-box/src/container/container.cpp
- apps/ll-box/src/container/mount/host_mount.cpp
- apps/ll-box/src/util/logger.cpp
- apps/ll-box/src/util/logger.h
- **fix(box): move finalize mounts to beginning of pivot root**
- **fix(box): default log level set to warning**
> fix some issue of ll-box

- libs/linglong/src/linglong/builder/linglong_builder.cpp
* Change the parameter of pullDependency from QString to FuzzyRefrence.
* If the version of base or runtime is not set tweak, we should not write the version with tweak to info.json.
Log:
> fix: the version of runtime is not fuzzy in info.json

- apps/ll-package-manager/src/main.cpp
remove ll-system-helper when use --no-dbus option
Log:
> fix: remove ll-system-helper when use --no-dbus option

- misc/share/applications/linglong-repair-tool.desktop
Using the icon 'deepin-repair-tools' which from deepin-icon-them.
Log:
> fix: use host icon for linglong-repair-tool

- misc/libexec/linglong/fetch-git-repo
> fix(builder): --init-branch is not available in git 2.20.1

- apps/ll-builder/src/main.cpp
1. fix the typo.
2. set the permission to 0644 if the templateFile is not exits.
Log:
> fix: the linglong.yaml after ll-builder create is readonly

- misc/CMakeLists.txt
Previously, misc/CMakeLists.txt installed the program linglong-repair-tool as a "FILES" item (no executable bit), this is incorrect as the user would fail to run this program (with a "permission denied" error).
Correct the INSTALL() command and install linglong-repair-tool as a "PROGRAMS" item to give it executable bit at install-time.
> fix(cmake): install linglong-repair-tool as a program

- apps/generators/90-legacy/src/main.cpp
mount /etc/timezone to container
Log:
> fix: timezone is error for linglong app

- apps/generators/90-legacy/src/main.cpp
This reverts commit 69efe374c5aa8016eb0463706c9cbe0315e7f9b4.
> Revert "fix: timezone is error for linglong app"

- libs/linglong/src/linglong/runtime/container.cpp
> fix: builder did not exit when the build script failed

- apps/ll-builder/src/main.cpp
- libs/linglong/src/linglong/utils/global/initialize.cpp
- libs/linglong/src/linglong/utils/global/initialize.h
日志重定向会导致应用检测到非tty环境, 关闭stderr日志输出
builder强制开启非tty环境的终端日志输出
Log:
> fix: builder log redirection losing error message

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
* Add ostreeSpecFromReferenceV2() which return
a string with the 'binary' module.
* Add getLayerQDirV2() which use ostreeSpecFromReferenceV2()
* Always use 'binary' first and fallback to 'runtime'
Log:
> refactor: using 'binary' as one of the module

- apps/ll-package-manager/src/main.cpp
package manager应该使用指针类型的ClientFactory
避免对象在函数返回后被销毁
Log:
> fix: Using pointer to prevent object destruction

- debian/linglong-bin.postinst
- debian/rules
- debian/sysctl.d/linglong.conf
ubuntu 24.04 has more limitation on unprivileged user namespace,so we have to disable them
Log:
> fix: failed to run linglong app in ubuntu 24.04

- apps/ll-box/src/main.cpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/runtime/container.cpp
- libs/linglong/src/linglong/runtime/container_builder.cpp
* Save env variables to /run/user/1000/linglong/$OCIRUNTIME/linglong99.sh and mount it to /etc/profile.d/linglong99.sh in container.
* Remove 'bash --login -c' from exec() of ll-box, we
add it before create container.
Log:
> fix: missed some env variables when reusing container

- libs/linglong/src/linglong/package/layer_packager.cpp
if layer file exist, we must remove it before export it, or layer will overlay
Log:
Resolve: https://github.com/linuxdeepin/developer-center/issues/9033
> fix: layer size error when export layer repeatedly

- CMakeLists.txt
- apps/uab/CMakeLists.txt
- debian/rules
* Rename ENABLE_UAB_HEADER to ENABLE_UAB.
* If ENABLE_UAB is not set, do not build uab-loader.
Log:
> fix: fix a warning during build deb

- libs/linglong/src/linglong/package/uab_packager.cpp
std::filesystem can not been declared in uos, so we need to add filesystem header
Log:
> fix: failed to package linglong in uos1071

- apps/ll-session-helper/src/main.cpp
- misc/share/linglong/builder/templates/appimage-url.yaml
url is download to linglong/sources, should enter linglong/sources to operate appimage file
Log:
> fix: ll-builder convert appimage error when use url

- libs/linglong/src/linglong/repo/ostree_repo.cpp
fix https://github.com/linuxdeepin/developer-center/issues/9416.
Log:
> fix: always use config.yaml to init ostree repo

- libs/linglong/src/linglong/runtime/container.cpp
- libs/linglong/src/linglong/runtime/container_builder.cpp
quote the values environment variables to avoid loading errors when some environment variables have multiple values, such as A=a;b
Log:
> fix: container env error when environment variables have multiple values

- libs/linglong/src/linglong/cli/cli.cpp
ll-cli install(upgrade) should return errcode according to lastStatus
Log:
> fix: ll-cli install return error errcode

- libs/linglong/src/linglong/package_manager/package_manager.cpp
在安装应用时按ctrl+c结束进程, package-manage 会异常退出
Log:
> fix: Canceling a task causes the package manager to crash.

- libs/linglong/src/linglong/repo/ostree_repo.cpp
ostree_repo_pull() will iterate the thread default main context, We new a new context before call ostree_repo_pull().
Log:
> fix: SIGBRT when installing two apps

- libs/linglong/src/linglong/cli/cli.cpp
If '--name' is not set, use the default name.
issue: https://github.com/linuxdeepin/developer-center/issues/10235
Log:
> fix(ll-cli): nothing changed if repo modify without '--name'

- libs/linglong/src/linglong/builder/linglong_builder.cpp
ll-builder 构建出来的玲珑应用没有拷贝出 linglong.yaml，不方便后续应用维护以及复现打包过程。
Log: copy linglong.yaml
> feat: copy linglong.yaml to output

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- misc/libexec/linglong/app-conf-generator
* Return error when execute app-conf-generator failed.
* Do not parse full line of Exec, just insert string after Exec=.
issue: https://github.com/linuxdeepin/developer-center/issues/10419
Log:
> fix(ll-builder): failed to generate desktop file

- apps/generators/40-host-ipc/src/main.cpp
- misc/lib/linglong/container/config.json
在制作flatpak的base时发现, flatpak的动态链接器 (ld-linux-x86-64.so.2)
只包含了/usr/lib/x86_64-linux-gnu这一个动态库搜索路径, 导致bash在运行ldconfig之前是无法启动的
所以在容器钩子中不再通过bash运行ldconfig而是直接启动ldconfig, 以兼容复杂的base环境
note: org.gnome.Platform/x86_64/43 和 org.kde.Platform/x86_64/5.15-23.08 都有这个问题
Log:
> feat: do not use bash to execute ldconfig

- libs/linglong/src/linglong/package/uab_packager.cpp
- libs/linglong/src/linglong/package/uab_packager.h
The std::hash specialization for std::filesystem::path has only been added as resolution of LWG issue 3657 into the standard draft.
This issue has been fixed in GCC 12:
https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=e3c5e8360b4e4799e1e2daf74282629248690f23.
So use std::unordered_set<std::string> instead of
std::unordered_set<std::filesystem::path> for compatibility with lower version of GCC.
> fix(uab): build failed below GCC 12

- apps/ll-builder/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
ll-builder extract do not need constructing an build instance, it is a static function, calling directly.
Log: fix ll-builder extract can not use normally
> fix: ll-builder failed to extract layer

- libs/linglong/src/linglong/package_manager/package_manager.cpp
Only need to pull dependencies when installing app, but not when installing runtime or base.
Log: fixed runtime or base layer can not install normally
> fix: failed to install runtime or base layer

- libs/linglong/src/linglong/package_manager/package_manager.cpp
Only need to download if base or runtime does not exist locally.
Log: fixed runtime or base can not pull normally
> fix: failed to pull runtime or base

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- two packages with the same version but different channels are not
- use type 'std::optional<std::string>' for subRef of UAB
> refactor: improve error message and fix some error

- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/package_manager/package_manager.h
- libs/linglong/src/linglong/package_manager/task.h
- libs/linglong/src/linglong/repo/ostree_repo.cpp
有用户反馈安装应用时会阻塞搜索命令的使用, 对此进行了排查
发现为修复同时执行多个安装任务导致manager异常退出的问题
在下载文件时使用g_main_context_new切换事件循环, 这会导致dbus服务无法处理调用, 同时也会导致下载进度无法通过dbus信号发出 本次改动去掉了g_main_context_new, 并通过taskRunning控制同时只执行一个安装任务 后续会将layer和uab的安装也加入到控制队列中
顺便修复因ostree_async_progress重用导致下载runtime不显示进度的问题
> fix: using queues to control install order

- apps/ll-box/src/container/mount/host_mount.cpp
- apps/ll-box/src/util/filesystem.h
when declare option 'copy-symlink' and 'nosymfollow' at the same time, box will apply 'nosymfollow' and ignore 'copy-symlink'.
> fix(box): adjust 'nosymfollow' priority to highest

- libs/linglong/src/linglong/package_manager/package_manager.cpp
任务队列会自动删除运行完毕的任务, 不在需要在每个任务清理自己
修复安装layer和uab报错的问题
Log:
> fix: remove duplicate task delete operations

- apps/generators/40-host-ipc/src/main.cpp
挂载软链接时添加copy-symlink参数,
修复使用crun作为运行时, 在执行build和run时报错的问题
Log:
> fix: unable to run and build applications using crun

- libs/linglong/src/linglong/builder/linglong_builder.cpp
目前的检查脚本未对runtime做适配, 在构建runtime时会报错
kind等于runtime时先跳过检查, 未来可能会为runtime添加对应的检查脚本
Log:
> feat: skip the check when kind is runtime

- apps/generators/90-legacy/src/main.cpp
bind /var/cache/fontconfig to container when run app
Log: fix app cannot display normally due to font cache
> fix: (temporary solution)the app cannot display normally due to font cache

- misc/CMakeLists.txt
Need to install linglong config file before create symlink.
Log: fix linglong config file is missing
> fix(config): linglong config symlink is missing

- libs/linglong/src/linglong/builder/linglong_builder.cpp
如果环境变量未设置std::getenv会返回空指针, std::string接收空指针会异常
Log:
> fix: an exception will occur when the LINGLONG_DEBUG does not set

- misc/lib/linglong/container/config.d/25-host-rootfs.json
Modify the mount permissions of a root filesystem, so that it allows applications to read and write files to the host file system. 
For example, deepin calendar needs to create a systemd timer in the ~/.cache/systemd directory, but ~/.cache directory is overlay by linglong, you can use /run/hosts/rootfs/home/xxx/.cache/systemd.
Bug: https://pms.uniontech.com/bug-view-271647.html
> feat: change the mount options of rootfs

- misc/script/linglong.sh
Change 'source' to '.', because '#/usr/bin/env bash' is not work in /etc/profile.d(Default is 'sh') and source is not supported in 'sh'.
Log:
> fix: failed to run linglong.sh

- apps/ll-box/src/container/mount/host_mount.cpp
当前ll-box运行容器时会报错ld.so.cache target不存在, 但base里面是存在这个文件的 排查后发现当前的ld.so.cache有两个挂载项, 一个是fix mount创建的base文件挂载, 另一个是为支持ldconfig实现的软链接挂载 因为fixmount最后会检查target重复的挂载项, 并进行删除, 这导致第一个fix mount创建的挂载记录被删除, 支持ldconfig实现的软链接挂载没有了挂载点
现在为设置nosymfollow的挂载项预先创建挂载点(如果挂载点不存在的话), 这和其他挂载行为保持一致, 避免挂载点不存在时ll-box报错
> fix: ll-box create mount point for nosymfollow

- api/schema/v1.json
- api/schema/v1.yaml
- apps/ll-builder/src/main.cpp
- libs/api/src/linglong/api/types/v1/BuilderConfig.hpp
- libs/api/src/linglong/api/types/v1/Generators.hpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
Some appimage packages use libraries in packages(LD_LIBRARY_PATH), it will cause the ldd check fails. so add build option to skip ldd check.
> feat(linglong_builder): add build option to skip ldd check

- libs/linglong/src/linglong/repo/ostree_repo.cpp
PackageInfoV2 packageInfoV2Module is not assignment when construction PackageInfoV2.
Log: fix ll-cli search abnormally
> fix(repo): ll-cli search result is abnormal

- debian/linglong-bin.install
- misc/CMakeLists.txt
deepin-linglong.xml rename vnd.linyaps.uab.xml, install file name should be modified synchronously.
> fix(config): failed to install uab mime-type file

- libs/linglong/src/linglong/package/reference.cpp
- libs/linglong/src/linglong/package/reference.h
- libs/linglong/src/linglong/package_manager/package_manager.cpp
* Use std::unordered_map<Reference>.
* Overload operators '==' and '!=' and specialization of std::hash in Reference.
Log:"
> fix: should not use std::map<Reference>

- debian/changelog
This reverts commit 866d6c18978e605e33101b766880a6ac75ee0c2a.
> Revert "chore: bump version to 1.6.3-1"

- libs/linglong/src/linglong/cli/cli.cpp
- misc/share/dbus-1/system.d/org.deepin.linglong.PackageManager1.conf
* Add some rules to the dbus conf of PM: For deepin-linglong and root, allow to call any method. For other users, they should not call any method instead of Search.
* Capture the error of dbus reply which from PM, if the error type is 'AccessDenied' notify pepole and return.
Log:
> fix!: restrict access to some methods of PM

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- misc/libexec/linglong/app-conf-generator
玲珑在构建后会使用app-conf-generator脚本修改应用的desktop, service等文件 在Exec字段添加ll-cli run实现通过玲珑启动应用, 减少应用开发者工作量
修复了在错误的share/systemd目录查找service，改为在lib/systemd目录查找 share/systemd目录是在执行完app-conf-generator后才从lib/systemd复制的 复制的原因是因为entries是指向share的软链接, systemd需要在entries中才会生效
Log:
> fix: systemd service file not revised correctly

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
deepin-manual path should be exported,
self-developed applications will installed files that will be accessed by the help manual.
> feat: add deepin-manual to export paths

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
- misc/share/dbus-1/system.d/org.deepin.linglong.PackageManager1.conf
Configuration() and setConfiguration() could be failed. Due to the limit of dbus permission policy, we should call runningAsRoot() before setConfiguration().
Log:
> fix: check dbus error after read/write the Property of PM

- apps/ll-builder/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/builder/linglong_builder.h
* We should keep the output format of 'll-builder repo show' as ll-cli.
* 'll-builder repo show' should return after print info. 
* 'linglong.yaml' is not necessary to 'll-builder import.
Log:
> fix(ll-builder): some minor bugs

- apps/ll-cli/src/main.cpp
- libs/linglong/src/linglong/cli/cli.cpp
* If there need migrate and the current operation is
not 'll-cli migrate', notify the message.
* Call runningAsRoot() before call migrate().
Log:
> fix: can not do the migration

- apps/ll-builder/src/main.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
ll-builder build的命令参数有重复的变量, 导致部分参数不生效
网络库在断网时没有返回准确的错误信息
> fix: ll-builder build command parameter error

- apps/generators/25-host-env/src/main.cpp
- libs/utils/src/linglong/utils/command/env.cpp
目前会通过profile.d/00env.sh将宿主机的PATH变量传递到容器中并覆盖profile文件设置的默认值
目前看来并没有好处, 反而会导致预料之外的问题, 比如在一些系统上PATH没有包含/bin目录, 但玲珑的base可能需要
> feat: not use the host machine PATH variable

- libs/linglong/src/linglong/cli/cli_printer.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
* Optimize output information of prune.
* If the module is runtime, it should be removed too.
Log:
> fix: some minor bugs of 'll-cli prune'

- misc/share/linglong/builder/templates/example.yaml
org.deepin.foundation do not have loong64 arch, so use org.deepin.base.
Bug: https://pms.uniontech.com/bug-view-284713.html
> fix(builder):example can not build in loong64 arch

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/package_manager/package_task.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
> fix: always search module 'binary' at first

- libs/linglong/src/linglong/package_manager/package_manager.cpp
If the version is set, do clearReference first. If exists, return with error.
Log:
> refactor: adjust Install() in ll-package-manager

- po/CMakeLists.txt
Custom target name can not be the same as po file.
> fix: CMakeLists config error

- misc/libexec/linglong/builder/helper/ldd-check.sh
ldd-check在检查之前应该刷新ldconfig缓存,
否则无法找到应用构建生成的so文件
> fix: ldd-check should run ldconfig first

- apps/ll-cli/src/main.cpp
--prune and --all options should be provided for compatibility with older command line parsing.
> fix(cli): can not uninstall app by app store

- apps/ll-cli/src/main.cpp
Use fallthrough to allow list,search,info,content sub command to support --json flags.
> fix(ll-cli): cli sub command will error when use --json flag

- apps/ll-cli/src/main.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
在迁移后重新导出所有应用的entries, 避免数据残留影响功能
> feat: re-export all application entries after migrate

- libs/linglong/src/linglong/repo/ostree_repo.cpp
> fix: unable to export all entries file

- libs/linglong/src/linglong/repo/repo_cache.cpp
If the repository or cache file is not damaged, rebuildCache should not fail.
Log:
> fix: failed to rebuildCache because of some invalid records

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
旧版本pkexec没有keep-cwd选项, 为兼容旧版本pkexec,
将相对路径的layer文件转为绝对路径
> feat: compatibility with older versions of pkexec

- apps/ll-builder/src/main.cpp
Some packaging build platforms use the '-f' option, we must provide for compatibility.
> fix(build): ll-builder build compatible with '-f' option

- apps/ll-builder/src/main.cpp
Option --repo-name should use correct variable.
> fix(build): ll-builder push can not working fine

- apps/ll-cli/src/main.cpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
- po/en_GB.po
- po/en_US.po
- po/es.po
- po/linyaps.pot
- po/zh_CN.po
Compatible with old versions to stop(enter) running app container using fuzz reference.
> fix(cli): ll-cli kill can not stop app by reference

- misc/libexec/linglong/builder/helper/symbols-strip.sh
剥离调试符号时应跳过已存在的debug文件, 这些文件可能是跟随deb导入的
> feat: skip debug files when stripping symbols

- libs/linglong/src/linglong/repo/ostree_repo.cpp
> fix: should be return when layer is not found

- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
- **fix: ignore version while creating PackageTask**
- **fix: access value to unexpected**
- **fix: remove symlink or empty directory before checkout**
> fix some errors

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
1. Develop module can not be installed without binary module.
2. Develop module should be remove when run uninstall app.
> fix(cli): can not install or uninstall develop module

- debian/linglong-bin.postinst
In linglong-bin.postrm, '>/dev/null' should be '2>dev/null'.
Log:
> fix: error message occurs in deb trigger

- libs/linglong/src/linglong/package_manager/package_manager.cpp
Use the correct logical operators to judge module.
> fix(cli): package manager pullDependency misjudgment

- libs/linglong/src/linglong/package_manager/package_task.cpp
- libs/utils/src/linglong/utils/global/initialize.cpp
- libs/utils/src/linglong/utils/global/initialize.h
修复builder在下载依赖时无法按Ctrl+C退出的问题
尝试使用QCoreApplication::aboutToQuit让任务停止没有效果, 所以使用了自定义的全局对象
> fix: ll-builder cannot exit while pulling dependency

- apps/ll-package-manager/src/main.cpp
tryMigrate should performe before construction ostree repo.
> fix(pm): migration not performed when update from old version

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
> feat: compatible with runtime module

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
If the layer dir is not exists, we just need to give a warning instead of return with error.
Log:
> fix: can not uninstall ref if layer dir is not exist

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
The interface org.freedesktop.DBus.Introspectable can not be rejected in dbus(1.12.20.11-deepin1). We use org.deepin.linglong.PackageManager.Prune to identify permissions now.
Log:
> fix: dbus permission authentication is skipped

- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/25_host_env.cpp
DTK使用XCURSOR_SIZE环境变量设置鼠标尺寸
需要将该环境变量从宿主机传递到容器中
> fix: abnormal cursor size in wayland

- .obs/workflows.yml
> feat: update obs workflows

- apps/ll-cli/src/main.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- tools/test-linglong.sh
获取远程模块列表时, 应该考虑兼容旧版本的runtime modules
优化安装和升级流程, 只安装单个模块时, 不需要提前获取远程模块列表
> fix: getRemoteModuleList for incompatibility with runtime modules

- misc/libexec/linglong/font-cache-generator
安装modules时, 因为缓存文件已存在, 创建目录会失败
> feat: cache generation failed when installing modules

- libs/linglong/src/linglong/package_manager/package_manager.cpp
无论是否存在未使用的runtime, 都清理一遍ostree仓库
> feat: optimize ll-cli prune command

- apps/ll-builder/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
ll-builder import命令支持传递目录, 这便于制作base和手动修改app
> feat: ll-builder supports import directory

- debian/linglong-bin.install
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
- libs/utils/src/linglong/utils/error/error.h
- misc/CMakeLists.txt
- misc/lib/systemd/user-generators/linglong-user-systemd-generator
- rpm/linglong.spec
XDG_DATA_DIRS下面的systemd优先级很高, 会影响系统systemd服务
将应用的systemd导出到其他地方, 再使用user-generator复制到优先级最低的generator.late目录
> feat: adjust systemd/user priority

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
Bring updateAM() back and call another service which in system bus. 
Service name is org.desktopspec.ApplicationUpdateNotifier1.
Log:
> fix: no desktop in launcher after install app

- CMakeLists.txt
- apps/ll-builder/src/main.cpp
- apps/ll-dialog/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/package_manager/package_manager.h
- libs/linglong/src/linglong/runtime/container.cpp
- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/90_legacy.cpp
- po/POTFILES.in
- po/en_GB.po
- po/en_US.po
- po/es.po
- po/linyaps.pot
- po/zh_CN.po
this is a temporary solution:
1. allow cache generation failure;
2. disable font cache generation.
> fix: can not install app in chroot

- apps/ll-builder/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/builder/linglong_builder.h
all checkers should execute at the container which based on binary layer
> fix: add runtimeCheck method for builder

- libs/linglong/src/linglong/runtime/container.cpp
- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/40_host_ipc.cpp
when host use systemd-resolved to manage dns and systemd-resolved working on stub mode, the file /etc/resolv.conf is a symlink to /run/systemd/resolve/stub-resolv.conf.
refactoring the process for normalization.
> fix: resolve the real path for some host files

- apps/ll-cli/src/main.cpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
Added a new `--all` flag to the search command to display all versions of packages. By default, search results will only show the latest version of each package.
> feat: filter search results to show only latest versions by default

- misc/libexec/linglong/builder/helper/symbols-strip.sh
之前在剥离调试符号的脚本中尝试跳过被剥离的调试符号文件,
但因判断条件错误, 导致未剥离调试符号的二进制文件也被跳过
> fix: debug symbols not stripped from build artifacts

- apps/ll-builder/src/main.cpp
- apps/ll-cli/src/main.cpp
- apps/ll-package-manager/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli_printer.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/repo/config.cpp
- libs/linglong/src/linglong/repo/config.h
- libs/linglong/src/linglong/repo/ostree_repo.cpp
OSTree still uses defaultRepo, but defaultRepo has now become an alias.
> fix: can't search after adding repo using alias

- libs/linglong/src/linglong/repo/ostree_repo.cpp
Do not update ostree repo config when open ostree repo,otherwise it will cause repo config permission error and only supports updating ostree repositories through ll-cli repo command.
> fix: ostree repo config permission error

- libs/linglong/src/linglong/cli/cli_printer.cpp
- po/en_GB.po
- po/en_US.po
- po/es.po
- po/linyaps.pot
- po/zh_CN.po
Previously, the `App` field in the `ll-cli ps` command output displayed the full package name (e.g., `main:org.dde.calendar/5.14.7.3/x86_64`). This has been updated to display only the AppID portion (e.g., `org.dde.calendar`).
> feat: `ll-cli ps` output to display only AppID in the App field

- apps/ll-cli/src/main.cpp
This commit ensures that `ll-cli` now outputs the standard `--help` information when no arguments are provided, aligning with common CLI conventions. 
The `--help-all` option remains available for users who need expanded details.
> fix: ll-cli outputs --help info instead of --help-all

- libs/linglong/src/linglong/repo/ostree_repo.cpp
add "--" to abort parameter parsing, the first "--" to abort COMMAND
option parsing, the second "--" will abort ll-cli run command parametor
parsing.
> fix: can not start app normally when there are extra parameters

- api/schema/v1.json
- api/schema/v1.yaml
- apps/ll-cli/src/main.cpp
- libs/api/src/linglong/api/types/v1/Generators.hpp
- libs/api/src/linglong/api/types/v1/Repo.hpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
- libs/linglong/src/linglong/cli/cli_printer.cpp
- libs/linglong/src/linglong/repo/config.cpp
- libs/linglong/src/linglong/repo/config.h
- misc/share/linglong/config.yaml
The default priority for the stable repository is 0. 
When adding a new repository, its priority will be set to the current minimum priority minus 100. 
If the new repository is set as the default repository, its priority will be set to the current maximum priority plus 100. 
Added the set-priority subcommand to allow manual specification of priorities (duplicates are not allowed).
> feat: add priority to the repo config

- libs/linglong/src/linglong/cli/cli.cpp
When all packages are up to date, the upgrade command does not automatically end
Issue: https://github.com/OpenAtom-Linyaps/linyaps/issues/1024
> fix: upgrade exception when all packages are up to date

- libs/linglong/src/linglong/cli/cli.cpp
A previous change to ps caused this problem.
> fix: enter command cannot enter the container

- debian/control
> fix: ll-bulder build dependent on fuse-overlay

- libs/linglong/src/linglong/repo/ostree_repo.cpp
Should use complete base name rather than base name.
> fix: rewrite file error

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
When adding and removing a repository, ostree's repo config isn't updated.
> fix: ostree config doesn't have the correct update

- libs/linglong/src/linglong/repo/ostree_repo.cpp
> feat: use getLayerDir when exporting

- libs/linglong/src/linglong/cli/cli_printer.cpp
Fix repo's output title and value do not align.
> fix: repo output is not aligned

- libs/linglong/src/linglong/repo/ostree_repo.cpp
Push crashes when getting the default repository.
> fix: builder push crash

- misc/lib/linglong/container/config.d/10-basics.json
Mount /tmp to tmpfs to prevent some files sharing.
> fix: app cannot be started immediately after exiting

- external/http/src/apiClient.c
- tools/openapi-c-libcurl-client/apiClient.c.mustache
Setting connection timeout is 1 second.
Issue: https://github.com/OpenAtom-Linyaps/linyaps/issues/1041
> fix: network exception waiting time is to long

- libs/linglong/src/linglong/cli/cli.cpp
Previously, packages with the same id but different module values were incorrectly treated as the same package, causing some to be lost. This fix ensures that (id, module) is used as the unique key, preserving all distinct packages while still filtering by version.
> fix: preserve packages with different modules while filtering by version

- libs/linglong/src/linglong/builder/linglong_builder.cpp
When copying relative symlinks pointing to existing directories, they were incorrectly turned into empty folders.
Issue: https://github.com/OpenAtom-Linyaps/linyaps/issues/1039
> fix: relative symlinks to directories from becoming empty folders

- libs/linglong/src/linglong/runtime/container_builder.cpp
- release.bash
only need to skip strictly equivalent path
> fix: correct path deduplication while fixmount

- libs/linglong/src/linglong/repo/ostree_repo.cpp
fix compiler error when use nlohmann from CPM
> fix: fix compiler error

- libs/linglong/src/linglong/builder/linglong_builder.cpp
skip fuse-overlayfs whiteout files which name starts with ".wh."
> fix: skip whiteout files

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
builder不再将systemd service导出到share目录,
避免因share优先级过高影响系统功能
> fix: exporting systemd service may cause system error

- libs/linglong/src/linglong/repo/repo_cache.cpp
Direct string comparisons should not be used.
> fix: version comparison error

- libs/linglong/src/linglong/builder/linglong_builder.cpp
Symbolic should only be created for directories.
> fix: ll-builder build failed

- libs/linglong/src/linglong/package/layer_packager.cpp
- libs/linglong/src/linglong/package/uab_file.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/utils/src/linglong/utils/overlayfs.cpp
Layer dir has been umount in
https://github.com/OpenAtom-Linyaps/linyaps/blob/619a93ea5ca8f9b7293e4dbff8b953f6b0ea7cb9/libs/linglong/src/linglong/package_manager/package_manager.cpp#L649, so do not need to umount again in LayerPackager destructor.
> fix: failed to umount layer dir

- libs/linglong/src/linglong/builder/linglong_builder.cpp
Increase the width of the packge under the builder Processing Dependency.
避免包名和版本挤在一起
> chore: adjust the builder output format

- apps/ll-builder/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/builder/linglong_builder.h
When exporting layer, add --no-develop to avoid exporting the develop module.
> feat: support don't export the develop module

- misc/lib/systemd/user-generators/linglong-user-systemd-generator
file or directory may not exist
> chore: suppress error while executing systemd-generator

- libs/linglong/src/linglong/repo/ostree_repo.cpp
old runtime module is equal to binary module
> fix: merge runtime module also

- CMakeLists.txt
- REUSE.toml
- apps/ll-builder-utils/CMakeLists.txt
- apps/ll-builder-utils/ll-builder-export
- apps/ll-builder-utils/patch/libfuse.patch
- apps/ll-builder/src/main.cpp
- apps/uab/CMakeLists.txt
- apps/uab/header/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/builder/linglong_builder.h
- libs/linglong/src/linglong/package/uab_packager.cpp
- libs/linglong/src/linglong/package/uab_packager.h
- linglong.yaml
1. export UAB add -o,--output option.
2. add ll-builder-utils to build uab-header and uab-loader, which is a linglong APP. To build ll-builder-utils, enable flag ENABLE_LINGLONG_APP_BUILDER_UTILS, and make ll-builder-utils.
4. ll-builder will try to use ll-builder-utils to export UAB file.
> Introduce ll-builder-utils to export UAB

- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
The lock file cannot be placed in /run/linglong directory. When switching to another user, there is no permission for the directory so the file should be placed in the /run/linglong/uid/ directory.
> fix: unable to start the app normally when switching accounts

- apps/ll-builder/src/main.cpp
When writing a version number incorrectly, it should return an error and exit instead of crashing directly.
> fix: builder build crash when parsing version number

- misc/share/zsh/vendor-completions/_ll-cli
Error: "_values:compvalues:11: not enough arguments"
> fix: zsh completion failed

- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp
Certificate name resolvtion is very complicated
we shouldn't bind /etc/ssl/certs to container directly
> fix: remove binding host certs for now

- libs/linglong/src/linglong/cli/cli.cpp
Added validation to ensure the content command can only be used with application layers by checking the layer kind. If the layer is not an app,
an error message is displayed to inform the user that only app content viewing is supported. This prevents potential issues when trying to view content of non-application layers.
fix: 限制内容命令仅用于应用类型层
添加验证以确保内容命令只能用于应用层，方法是检查层的类型。
如果该层不是应用类型，则显示错误消息，通知用户只支持查看应用内容。
这可以防止尝试查看非应用层内容时可能出现的问题。
> fix: restrict content command to app type layers only

- api/schema/v1.json
- api/schema/v1.yaml
- apps/ll-cli/src/main.cpp
- libs/api/src/linglong/api/types/v1/Generators.hpp
- libs/api/src/linglong/api/types/v1/LinglongAPIV1.hpp
- libs/api/src/linglong/api/types/v1/PackageInfoV2.hpp
- libs/api/src/linglong/api/types/v1/PackageManager1JobInfo.hpp
- libs/api/src/linglong/api/types/v1/PackageManager1PruneResult.hpp
- libs/api/src/linglong/api/types/v1/PackageManager1SearchParameters.hpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
- libs/linglong/src/linglong/cli/cli_printer.cpp
- libs/linglong/src/linglong/cli/cli_printer.h
- libs/linglong/src/linglong/cli/json_printer.h
- libs/linglong/src/linglong/cli/printer.h
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
1. Added repository field to search parameters requiring specifying
repos to search
2. Modified search implementation to support searching in multiple
repositories
3. Restructured search results to group packages by repository source
4. Added --repo option to the CLI search command
5. Updated display format to show repository information in search
results
6. Improved filtering logic to work with the repository-grouped package
structure
7. Added PackageManager1PruneResult type to separate it from search
results
> feat: enhance package search with multi-repository support

- misc/share/bash-completion/completions/ll-cli
- misc/share/zsh/vendor-completions/_ll-cli
This change enhances both bash and zsh completions for the ll-cli tool by:
1. Adding a new function to specifically list installed applications
2. Updating the run, uninstall, and content commands to show only apps in their tab completion suggestions instead of all installed components
3. Making the completion more contextually relevant for these commands
> feat: improve shell completions to show only apps when appropriate

- libs/linglong/src/linglong/cli/cli.cpp
This change optimizes the version filtering process by:
1. Replacing QString::fromStdString() with direct c_str() calls to eliminate unnecessary string conversions
2. Directly updating existing entries instead of creating temporary maps
3. Adding proper checks when updating package repositories to prevent overwriting existing entries
> fix: improve package version filtering logic

- libs/linglong/src/linglong/cli/json_printer.cpp
- libs/linglong/src/linglong/cli/json_printer.h
Added implementation for JSONPrinter::printMessage method to output messages
in JSON format. The method serializes the message as a JSON object with a
"message" property. This enhances the JSON output capability by properly handling messages alongside other data types.
> feat: implement printMessage method for JSONPrinter

- api/schema/v1.json
- api/schema/v1.yaml
- apps/ll-cli/src/main.cpp
- libs/api/src/linglong/api/types/v1/Generators.hpp
- libs/api/src/linglong/api/types/v1/PackageManager1InstallParameters.hpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
- libs/linglong/src/linglong/package/layer_packager.cpp
- libs/linglong/src/linglong/package/reference.h
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/package_manager/package_manager.h
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
- libs/utils/src/linglong/utils/error/error.h
1. Added `--repo` option to CLI for selecting specific repositories
2. Modified installation process to install from specified repositories
3. Enhanced repository priority management with temporary priority boost
4. Added repository awareness to package upgrade process
5. Improved remote reference resolution across multiple repositories
6. Added new error code for modules not found remotely
> feat: implement multi-repository installation and upgrade

- apps/ll-builder/src/main.cpp
Do not support lzma compressor in uos v20.
> fix: layer file can not install in uos v20

- libs/linglong/src/linglong/repo/ostree_repo.cpp
std::filesystem::creat_directories does not treated this as an error
> fix: returns only if creating directories failed

- libs/linglong/src/linglong/package_manager/package_manager.cpp
Should not terminate the update task when the sub-state is PackageManagerDone.
> fix: update task ends abnormally when there is an application running

- libs/linglong/src/linglong/repo/ostree_repo.cpp
update-desktop-database and update-mime-database will generate system files in specify a directory. these files do not belong to the applications and should not be printed in the log.
> fix: uninstall application exception output log

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/package/uab_packager.cpp
…kager and Builder
Changed the size type from int to int64_t in both Builder and UABPackager to ensure proper handling of larger values. Additionally, initialized struct stat variables to improve code clarity and maintainability.
> fix: update size type to int64_t and initialize struct stat in calculateDirectorySize

- misc/lib/linglong/generate-xdg-data-dirs.sh
Path "/usr/local/share:/usr/share" must be set when XDG_DATA_DIRS is empty.
> fix: failed to export XDG_DATA_DIRS enviroment

- libs/linglong/src/linglong/cli/cli.cpp
Added missing return statements after loop.exit() calls in the prune command
to prevent function execution from continuing after exit is called. This fixes a crash that occurred when the function continued executing code after
requesting the event loop to exit, potentially accessing invalid memory.
> fix: prevent crash in prune command after loop exit

- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/runtime/container.cpp
- libs/utils/src/linglong/utils/bash_quote.h
use quoteBashArg if run with bash -c or write to bash script.
> fix: correctly pass argument by vector

- misc/CMakeLists.txt
Use `CMAKE_INSTALL_FULL_LIBEXECDIR` so that setting `CMAKE_INSTALL_LIBEXECDIR` changes `LIBEXEC_LINGLONG_DIR` accordingly.
> fix: don't hardcode libexec dir

- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/builder/linglong_builder.h
- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp
- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.h
Mounting may fail if the file types differed between the layer and host (e.g., regular file vs. symbolic link).
Implemented solution through two approaches
1. Build phase: Proactively remove /etc/localtime from build layer during overlayfs preparation to prevent conflicts with host timezone file mounting.
2. Container configuration: Introduced dedicated buildMountLocalTime method to handle timezone mounts, with enableSelfAdjustingMount properly managing these cases.
> fix: ensure correct /etc/localtime mounting

- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp
- misc/lib/linglong/container/README.md
Previously, app-specific patches were identified by matching the patch filename (without the extension) against the application ID. This approach was flawed as it caused patch conflicts between different applications. For example, a patch named `com.app.A.json`, intended only for `com.app.A`, would be incorrectly applied as a global patch to `com.app.B`.
This commit introduces a directory-based mechanism to correctly isolate application-specific patches. All patches for a specific app must now reside within a subdirectory named after the app ID.
> fix: Isolate app-specific patches in dedicated directories

- libs/linglong/src/linglong/package/layer_packager.cpp
1. Added QTemporaryDir and fstream headers for temporary file operations
2. Implemented fallback mechanism when direct file descriptor access fails
3. Added UUID-based temporary file naming for layer files
4. Improved error handling for file save operations
The changes address cases where direct access to file descriptors via /proc may fail (common in containerized environments). The new implementation first attempts direct access, then falls back to copying the file to a temporary location if needed. This makes the unpacking process more robust across different environments.
fix: 修复层解包中文件描述符访问问题
1. 添加 QTemporaryDir 和 fstream 头文件以支持临时文件操作
2. 当直接文件描述符访问失败时实现回退机制
3. 为layer文件添加基于UUID的临时文件命名
4. 改进文件保存操作的错误处理
这些改动解决了通过/proc直接访问文件描述符可能失败的情况（在容器环境中常
见）。新实现首先尝试直接访问，如果需要则回退到将文件复制到临时位置。这使 …
> fix: handle file descriptor access in layer unpacking

- apps/ll-init/src/ll-init.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
The init process will now exit with the same code as the initial child process it manages.  This is crucial for environments like the builder, where the success or failure of a command must be detected.
Add missing LINYAPS_INIT_SINGLE_MODE in handling process build depends.
> fix: Return exit code of initial child process

- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/repo/ostree_repo.h
Extracted the common OSTree pull options initialization code into a separate method initOStreePullOptions to avoid code duplication. The method handles:
1. Creating GVariantBuilder with common options
2. Setting refs and user agent
3. Disabling static deltas by default This change makes the pull operation code cleaner and more maintainable by centralizing the options configuration logic.
refactor: 提取 OSTree 拉取选项初始化代码
将 OSTree 拉取选项的初始化代码提取到单独的 initOStreePullOptions 方法中 以避免重复代码。该方法处理：
1. 创建带有通用选项的 GVariantBuilder
2. 设置refs和user-agent
3. 默认禁用静态增量 通过集中管理选项配置逻辑，使拉取操作代码更清晰且更易于维护。
> refactor: extract OSTree pull options initialization

- libs/linglong/src/linglong/cli/cli.cpp
- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.cpp
- libs/oci-cfg-generators/src/linglong/oci-cfg-generators/container_cfg_builder.h
Use this annotation with ll-box to configure ns_last_pid in new pid namespace to avoid pid collisions.
> feat: set ns_last_pid annotation

- libs/linglong/src/linglong/package/layer_packager.cpp
- libs/linglong/src/linglong/package/layer_packager.h
- libs/linglong/src/linglong/package/uab_file.cpp
- libs/linglong/src/linglong/package/uab_file.h
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/tests/ll-tests/CMakeLists.txt
- libs/linglong/tests/ll-tests/src/linglong/package/layer_packager_test.cpp
- libs/linglong/tests/ll-tests/src/linglong/package/uab_file_test.cpp
- libs/utils/src/linglong/utils/command/env.cpp
- libs/utils/src/linglong/utils/command/env.h
- tools/generate-coverage.sh
1. Changed LayerPackager to use std::filesystem::path instead of QDir for workDir
2. Added defensive programming in initWorkDir to handle multiple calls
3. Implemented proper cleanup in UABFile destructor for mount points and unpacked files
4. Added support for both erofsfuse and fsck.erofs unpack methods
5. Improved error handling and added new utility methods in UABFile
6. Added comprehensive unit tests for UAB file operations
refactor: 改进UAB文件处理和清理
1. 将LayerPackager中的workDir从QDir改为std::filesystem::path
2. 在initWorkDir中添加防御性编程以处理多次调用
3. 在UABFile析构函数中实现挂载点和解压文件的正确清理
4. 添加对erofsfuse和fsck.erofs两种解压方法的支持
5. 改进错误处理并在UABFile中添加新的实用方法
6. 为UAB文件操作添加全面的单元测试
> refactor: improve UAB file handling and cleanup

- .github/workflows/build.yaml
- CMakeLists.txt
- libs/linglong/src/linglong/package/layer_packager.cpp
- libs/linglong/src/linglong/package/layer_packager.h
1. Remove unused qcontainerfwd.h header to eliminate dead code
2. Split UUID generation and string conversion for better readability
3. Reformat mkfs.erofs command arguments for improved code style
4. Add missing filesystem header include to fix potential compilation issues
refactor: 改进层打包器代码组织
1. 移除未使用的 qcontainerfwd.h 头文件以消除死代码
2. 分离 UUID 生成和字符串转换以提高可读性
3. 重新格式化 mkfs.erofs 命令参数以改善代码风格
4. 添加缺失的 filesystem 头文件包含以修复潜在编译问题
> refactor: improve code organization in layer packager

- misc/libexec/linglong/fetch-file-source
1. Changed the method for copying cached files to the output file from `cp` to `cp --remove-destination --link`.
2. This introduces hard links instead of full copies, significantly improving performance when fetching files from the cache.  A fallback `cp` is included to handle cases where hard linking might fail (e.g., due to filesystem limitations).
3. The `--remove-destination` option ensures that if the destination file already exists, it's removed before creating the hard link, preventing errors.
Log: Improved file fetching performance by utilizing hard links for cached files
Influence:
1. Verify that files fetched from the cache are functionally identical before and after the change.
2. Measure the performance of file fetching (time taken) with and without the hard link optimization. …
> fix: Optimize file fetching with hard links

- api/schema/v1.json
- api/schema/v1.yaml
- libs/api/src/linglong/api/types/v1/ContainerProcessStateInfo.hpp
- libs/api/src/linglong/api/types/v1/Generators.hpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli_printer.cpp
- libs/linglong/src/linglong/package/fuzzy_reference.cpp
- libs/linglong/src/linglong/package_manager/package_manager.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
- libs/linglong/src/linglong/runtime/run_context.cpp
- libs/utils/src/linglong/utils/error/error.h
This refactoring moves the core uninstall logic from the cli to PM.
Key changes:
- Support uninstall extension
- Added robust error handling for uninstalling:
- Returns an error if multiple versions are installed and the user input is ambiguous.
- Prevents uninstalling 'base' or 'runtime' packages directly.
- Checks if an application or its dependencies are running before proceeding.
> refactor: Move uninstall logic to package manager service

- apps/ll-cli/src/main.cpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/cli/cli.h
- libs/linglong/src/linglong/runtime/run_context.cpp
- libs/linglong/src/linglong/runtime/run_context.h
1. Add `--base` option to specify the base layer.
2. Add `--runtime` option to specify the runtime.
3. Modify `RunContext::resolve` to utilize the `--base` and `--runtime` options.
4. Update builder resolution to pass base and runtime references.
5. Add logging for base and runtime resolution
Log: Added command-line options to specify the base and runtime for application execution.
Influence:
1. Test application execution with different base layers.
2. Verify that specifying a runtime overrides the default runtime.
3. Ensure that the `--base` and `--runtime` options are respected during application resolution.
4. Check that the logging accurately reflects the used base and runtime.
feat: 为 ll-cli 添加 base 和 runtime 选项
1. 添加 --base 选项来指定基础层
2. 添加 --runtime 选项来指定运行时环境
3. 修改 …
> feat: add base and runtime options

- apps/ll-cli/src/main.cpp
- libs/linglong/src/linglong/cli/cli.cpp
- libs/linglong/src/linglong/repo/ostree_repo.cpp
1. Fixed inverted logic in list command for showing upgrade list vs regular package list
2. Added sorting by package ID for both regular list and upgrade list outputs
3. Replaced Qt logging with linglong's custom logging in ostree repository
4. Maintained existing filtering functionality by package type
Log: Fixed package list display logic and improved sorting
Influence:
1. Test ll-cli list command without parameters to show installed packages
2. Test ll-cli list --upgradable to show available upgrades
3. Verify package sorting by ID in both list modes
4. Test package type filtering with --type parameter
5. Verify installation time display in package list
6. Confirm error handling for repository access issues
fix: 修复列表命令逻辑和日志记录
1. 修复了显示升级列表与常规包列表的反向逻辑
2. 为常规列表和升级列表输出添加了按包ID排序功能
3. …
> fix: correct list command logic and logging

- api/schema/v1.json
- api/schema/v1.yaml
- libs/api/src/linglong/api/types/v1/BuilderProjectSource.hpp
- libs/api/src/linglong/api/types/v1/Generators.hpp
- libs/linglong/src/linglong/builder/linglong_builder.cpp
- libs/linglong/src/linglong/builder/source_fetcher.cpp
- libs/linglong/src/linglong/builder/source_fetcher.h
- libs/linglong/tests/ll-tests/CMakeLists.txt
- libs/linglong/tests/ll-tests/src/linglong/builder/source_fetcher_test.cpp
- libs/linglong/tests/ll-tests/src/linglong/mocks/command.h
- libs/linglong/tests/ll-tests/src/linglong/utils/command_test.cpp
- libs/utils/src/linglong/utils/command/cmd.cpp
- libs/utils/src/linglong/utils/command/cmd.h
- misc/libexec/linglong/fetch-git-source
- tools/codegen.sh
1. Add environment variable support to Cmd class for process execution
2. Set GIT_SUBMODULES=true when executing source fetch scripts
3. Conditionally execute git submodule commands based on GIT_SUBMODULES env var
4. Fix member variable naming in Cmd class (command -> m_command)
5. Pass environment variables to command existence checking process
This change allows git submodules to be fetched only when explicitly enabled through the GIT_SUBMODULES environment variable, providing better control over the source fetching process. The environment variable mechanism was added to the Cmd utility class to support this feature, and existing command execution logic was updated to use proper member variable naming conventions.
Log: Added conditional git submodule fetching support in source fetcher …
> feat: enable git submodule fetching with environment variable control
